# Generated by Django 5.2.15 on 2026-09-20 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0020_remove_sitesettings_shipping_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotions_enabled', models.BooleanField(default=True, help_text='خاموش: هیچ تخفیف خودکاری روی قیمت\u200cها اعمال نمی\u200cشود (کدهای تخفیف از این کلید مستقل\u200cاند).', verbose_name='تخفیف\u200cهای خودکار فعال باشند')),
                ('apply_to_vip', models.BooleanField(default=False, help_text='فقط مخصوص تخفیف‌های خودکار (Promotion)؛ روی کدهای تخفیف اثری ندارد. کاربران با سطح قیمت ۳ به بالا (قیمت همکار). پیش‌فرض خاموش تا روی قیمت همکار تخفیف اضافه نشود و حاشیه‌ی سود منفی نشود.', verbose_name='تخفیف‌های خودکار روی قیمت کاربران سطح ویژه هم اعمال شود')),
                ('apply_for_cash', models.BooleanField(default=True, verbose_name='برای پرداخت نقدی اعمال شود')),
                ('apply_for_check', models.BooleanField(default=True, verbose_name='برای پرداخت چکی اعمال شود')),
                ('promotion_stacking', models.CharField(choices=[('best', 'بهترین تخفیف (فقط تخفیفی که بیشترین صرفه را برای خریدار دارد)'), ('stack', 'جمع\u200cشونده (همه\u200cی تخفیف\u200cهای مشمول به\u200cترتیب اولویت روی هم اعمال شوند)')], default='best', help_text='وقتی چند تخفیف هم\u200cزمان روی یک کالا مشمول\u200cاند.', max_length=10, verbose_name='ترکیب تخفیف\u200cهای هم\u200cپوشان')),
                ('max_item_discount_percent', models.PositiveSmallIntegerField(default=90, help_text='مجموع تخفیف\u200cهای خودکار روی یک واحد کالا هیچ\u200cوقت از این درصدِ قیمت پایه بیشتر نمی\u200cشود.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='سقف تخفیف روی هر کالا (درصد از قیمت پایه)')),
                ('rounding_step', models.PositiveIntegerField(choices=[(1, 'تومان'), (100, 'صد تومان'), (1000, 'هزار تومان')], default=1, help_text='قیمت نهایی تخفیف\u200cخورده به نزدیک\u200cترین مضرب این مقدار گرد می\u200cشود (هرگز بالاتر از قیمت پایه نمی\u200cرود).', verbose_name='گردکردن قیمت تخفیف\u200cخورده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'سیاست تخفیف',
                'verbose_name_plural': 'سیاست تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('kind', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت (کسر از قیمت هر واحد)'), ('special_price', 'قیمت ویژه (قیمت هر واحد = مقدار)')], default='percent', max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.PositiveIntegerField(help_text='درصدی: عدد ۱ تا ۹۹؛ مبلغ ثابت و قیمت ویژه: تومان.', verbose_name='مقدار')),
                ('max_discount_amount', models.PositiveIntegerField(blank=True, help_text='فقط برای نوع درصدی؛ خالی = بدون سقف.', null=True, verbose_name='سقف مبلغ تخفیف برای هر واحد (تومان)')),
                ('starts_at', models.DateTimeField(verbose_name='شروع')),
                ('ends_at', models.DateTimeField(verbose_name='پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('priority', models.SmallIntegerField(default=0, help_text='عدد بزرگ\u200cتر = اولویت بیشتر (برای تساوی در حالت «بهترین» و ترتیب اعمال در حالت «جمع\u200cشونده»).', verbose_name='اولویت')),
                ('login_required', models.BooleanField(default=False, verbose_name='فقط برای کاربران واردشده')),
                ('min_loyalty_level', models.PositiveSmallIntegerField(choices=[(0, 'همه (بدون محدودیت سطح)'), (1, 'سطح «برنزی» و بالاتر'), (2, 'سطح «نقره\u200cای» و بالاتر'), (3, 'سطح «طلایی» و بالاتر'), (4, 'سطح «الماسی» و بالاتر')], default=0, help_text='بر اساس تعداد سفارش\u200cهای پرداخت\u200cشده\u200cی کاربر (نیازمند ورود).', verbose_name='حداقل سطح وفاداری')),
                ('price_levels', models.CharField(blank=True, help_text='مثلاً «1,2» (سطح قیمت ۱ و ۲)؛ خالی = همه\u200cی سطوح. مهمان سطح ۱ حساب می\u200cشود.', max_length=40, verbose_name='فقط برای این سطوح قیمت')),
                ('payment_method', models.CharField(blank=True, choices=[('', 'همه\u200cی روش\u200cها'), ('cash', 'فقط پرداخت نقدی'), ('check', 'فقط پرداخت چکی')], default='', max_length=10, verbose_name='روش پرداخت')),
                ('show_in_flash_deals', models.BooleanField(default=True, help_text='فقط تخفیف\u200cهای عمومی (بدون شرط ورود/سطح/روش پرداخت) در باکس نشان داده می\u200cشوند. برای تخفیف «کل فروشگاه» معمولاً خاموش کنید.', verbose_name='نمایش در باکس «شگفت\u200cانگیز»')),
                ('badge_label', models.CharField(blank=True, max_length=60, verbose_name='برچسب نمایشی (اختیاری)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'تخفیف خودکار',
                'verbose_name_plural': 'تخفیف\u200cهای خودکار',
                'ordering': ('-starts_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PromotionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('all', 'کل فروشگاه'), ('product', 'محصول'), ('category', 'دسته\u200cبندی'), ('brand', 'برند')], default='product', max_length=10, verbose_name='نوع هدف')),
                ('include_descendants', models.BooleanField(default=True, help_text='فقط برای هدف «دسته\u200cبندی».', verbose_name='شامل زیردسته\u200cها')),
                ('is_exclusion', models.BooleanField(default=False, verbose_name='استثنا (از شمول خارج شود)')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.brand', verbose_name='برند')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.category', verbose_name='دسته\u200cبندی')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product', verbose_name='محصول')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='promotions.promotion', verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'هدف تخفیف',
                'verbose_name_plural': 'اهداف تخفیف',
                'ordering': ('is_exclusion', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', True), ('category__isnull', True), ('product__isnull', True), ('target_type', 'all')), models.Q(('brand__isnull', True), ('category__isnull', True), ('product__isnull', False), ('target_type', 'product')), models.Q(('brand__isnull', True), ('category__isnull', False), ('product__isnull', True), ('target_type', 'category')), models.Q(('brand__isnull', False), ('category__isnull', True), ('product__isnull', True), ('target_type', 'brand')), _connector='OR'), name='promotion_target_matches_its_type')],
            },
        ),
    ]
