# Generated by Django 5.2.15 on 2026-09-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_delete_discount'),
        ('promotions', '0002_migrate_legacy_discounts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promotiontarget',
            name='promotion_target_matches_its_type',
        ),
        migrations.AddConstraint(
            model_name='promotiontarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', True), ('category__isnull', True), ('product__isnull', True), ('target_type', 'all')), models.Q(('brand__isnull', True), ('category__isnull', True), ('target_type', 'product')), models.Q(('brand__isnull', True), ('product__isnull', True), ('target_type', 'category')), models.Q(('category__isnull', True), ('product__isnull', True), ('target_type', 'brand')), _connector='OR'), name='promotion_target_has_no_extra_links'),
        ),
    ]
