# Generated by Django 5.2.15 on 2026-09-20 14:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_seed_divisions_and_zones'),
        ('products', '0021_delete_discount'),
        ('promotions', '0003_relax_target_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discountpolicy',
            name='coupon_attempt_window_minutes',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='بازه\u200cی شمارش تلاش ناموفق (دقیقه)'),
        ),
        migrations.AddField(
            model_name='discountpolicy',
            name='coupon_max_invalid_attempts',
            field=models.PositiveSmallIntegerField(default=10, help_text='برای هر کاربر و هر IP جدا؛ بعد از رسیدن به سقف تا پایان بازه نمی\u200cتواند کد وارد کند.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='سقف تلاش ناموفق برای وارد کردن کد (در هر بازه)'),
        ),
        migrations.AddField(
            model_name='discountpolicy',
            name='coupon_reservation_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='ظرفیت کد تا پرداخت (یا پایان این مهلت) برای همان سفارش رزرو می\u200cماند؛ سفارش پرداخت\u200cنشده بعد از مهلت، ظرفیت را آزاد می\u200cکند. لغو سفارش بلافاصله آزاد می\u200cکند.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name='مهلت رزرو کد پس از ثبت سفارش (دقیقه)'),
        ),
        migrations.AddField(
            model_name='discountpolicy',
            name='free_shipping_rules_enabled',
            field=models.BooleanField(default=True, help_text='کلید سراسری: خاموش = هیچ قاعده\u200cی ارسال رایگانی (حتی فعال\u200cها) اعمال نمی\u200cشود. حداقل مبلغ و بازه\u200cی هر قاعده جدا در «قاعده\u200cهای ارسال رایگان» تنظیم می\u200cشود. ارسال رایگانِ پرچم کالا و کد «ارسال رایگان» از این کلید مستقل\u200cاند.', verbose_name='قاعده\u200cهای ارسال رایگان فعال باشند'),
        ),
        migrations.AddField(
            model_name='discountpolicy',
            name='free_shipping_threshold_after_coupon',
            field=models.BooleanField(default=True, help_text='روشن (پیش\u200cفرض، سود خالص سفارش را تضمین می\u200cکند): مبلغ سبد = پس از تخفیف خودکار و پس از کد تخفیفِ کالا. خاموش: فقط پس از تخفیف\u200cهای خودکار (کد تخفیف روی این شرط اثر ندارد).', verbose_name='حداقل مبلغ سبد پس از کد تخفیفِ کالا هم سنجیده شود'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='خالی = تولید خودکار. کد همیشه با حروف بزرگ لاتین و ارقام لاتین ذخیره می\u200cشود؛ مشتری با هر حالتی تایپ کند (حروف کوچک، ارقام فارسی) معتبر است.', max_length=40, unique=True, verbose_name='کد')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیح داخلی')),
                ('kind', models.CharField(choices=[('percent', 'درصدی (با سقف مبلغ)'), ('fixed', 'مبلغ ثابت'), ('free_shipping', 'ارسال رایگان (پیک درون\u200cشهری)')], default='percent', max_length=15, verbose_name='نوع')),
                ('value', models.PositiveIntegerField(default=0, help_text='درصد (۱ تا ۱۰۰) یا مبلغ (تومان). برای «ارسال رایگان» نادیده گرفته می\u200cشود.', verbose_name='مقدار')),
                ('max_discount_amount', models.PositiveIntegerField(blank=True, help_text='فقط برای نوع درصدی.', null=True, verbose_name='سقف مبلغ تخفیف (تومان)')),
                ('scope', models.CharField(choices=[('cart', 'کل سبد'), ('items', 'فقط محصولات/دسته\u200cهای انتخاب\u200cشده')], default='cart', max_length=10, verbose_name='شمول')),
                ('min_cart_amount', models.PositiveIntegerField(default=0, help_text='مبلغ کل کالاهای سبد *پس از* کسر تخفیف\u200cهای خودکار. ۰ = بدون حداقل.', verbose_name='حداقل مبلغ سبد (تومان)')),
                ('allow_with_promotions', models.BooleanField(default=False, help_text='خاموش (پیش\u200cفرض): کوپن فقط روی اقلامِ بدون تخفیف خودکار اعمال می\u200cشود.', verbose_name='با اقلام دارای تخفیف خودکار ترکیب شود')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع اعتبار')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان اعتبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('total_limit', models.PositiveIntegerField(blank=True, help_text='خالی = نامحدود.', null=True, verbose_name='سقف کل دفعات استفاده')),
                ('per_user_limit', models.PositiveIntegerField(blank=True, default=1, help_text='خالی = نامحدود.', null=True, verbose_name='سقف استفاده برای هر کاربر')),
                ('first_order_only', models.BooleanField(default=False, verbose_name='فقط برای اولین خرید')),
                ('audience', models.CharField(choices=[('everyone', 'همه\u200cی کاربران وارد\u200cشده'), ('assigned', 'فقط کاربرانی که کد برایشان تعریف شده')], default='everyone', max_length=10, verbose_name='مخاطب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('categories', models.ManyToManyField(blank=True, help_text='شامل همه\u200cی زیردسته\u200cها.', related_name='+', to='products.category', verbose_name='دسته\u200cهای مشمول')),
                ('products', models.ManyToManyField(blank=True, related_name='+', to='products.product', verbose_name='محصولات مشمول')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FreeShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان قاعده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('min_cart_total', models.PositiveIntegerField(default=0, help_text='۰ = بدون حداقل.', verbose_name='حداقل مبلغ سبد (تومان)')),
                ('starts_at', models.DateTimeField(blank=True, help_text='خالی = از همین حالا.', null=True, verbose_name='شروع')),
                ('ends_at', models.DateTimeField(blank=True, help_text='خالی = بدون پایان.', null=True, verbose_name='پایان')),
                ('postage_mode', models.CharField(choices=[('ignore', 'فقط پیک؛ ارسال با پست (پس\u200cکرایه) بدون تغییر'), ('cover', 'هزینه\u200cی پست را فروشگاه بپردازد (پست هم رایگان شود)')], default='ignore', max_length=10, verbose_name='ارسال با پست')),
                ('priority', models.SmallIntegerField(default=0, help_text='وقتی چند قاعده مشمول است، اولویت بالاتر برچسب را تعیین می\u200cکند.', verbose_name='اولویت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('cities', models.ManyToManyField(blank=True, related_name='+', to='locations.city', verbose_name='شهرها')),
                ('provinces', models.ManyToManyField(blank=True, related_name='+', to='locations.province', verbose_name='استان\u200cها')),
            ],
            options={
                'verbose_name': 'قاعده\u200cی ارسال رایگان',
                'verbose_name_plural': 'قواعد ارسال رایگان',
                'ordering': ('-priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True, verbose_name='شماره سفارش')),
                ('code', models.CharField(max_length=40, verbose_name='کد (اسنپ\u200cشات)')),
                ('status', models.CharField(choices=[('reserved', 'رزرو\u200cشده (در انتظار پرداخت)'), ('redeemed', 'مصرف\u200cشده'), ('released', 'آزادشده')], db_index=True, default='reserved', max_length=10, verbose_name='وضعیت')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='تخفیف کالاها')),
                ('shipping_discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='تخفیف ارسال')),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان رزرو')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان مهلت رزرو')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان مصرف نهایی')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان آزادسازی')),
                ('release_reason', models.CharField(blank=True, default='', max_length=30, verbose_name='دلیل آزادسازی')),
                ('over_limit', models.BooleanField(default=False, verbose_name='پرداخت پس از پایان مهلت و خارج از سقف')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.coupon', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مصرف کد تخفیف',
                'verbose_name_plural': 'مصرف کدهای تخفیف',
                'ordering': ('-reserved_at', '-id'),
                'indexes': [models.Index(fields=['coupon', 'status'], name='redemption_coupon_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='redemption_discount_gte_0'), models.CheckConstraint(condition=models.Q(('shipping_discount__gte', 0)), name='redemption_shipping_discount_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('admin', 'تخصیص توسط مدیر'), ('claimed', 'دریافت توسط کاربر'), ('auto', 'صدور خودکار')], default='admin', max_length=10, verbose_name='منبع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تخصیص')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='promotions.coupon', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_assignments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کد تخصیص\u200cیافته به کاربر',
                'verbose_name_plural': 'کدهای تخصیص\u200cیافته به کاربران',
                'constraints': [models.UniqueConstraint(fields=('coupon', 'user'), name='unique_coupon_per_user')],
            },
        ),
    ]
