# Generated by Django 5.2.15 on 2026-09-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_coupons_and_free_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='claim_limit',
            field=models.PositiveIntegerField(blank=True, help_text='حداکثر چند کاربر می\u200cتوانند این کد را دریافت کنند (جدا از سقف تعداد مصرف). خالی = نامحدود.', null=True, verbose_name='سقف تعداد دریافت\u200cکنندگان'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_claimable',
            field=models.BooleanField(default=False, help_text='کد فقط برای کاربرانِ واجد شرایط در صفحه\u200cی «دریافت کد تخفیف جدید» فهرست می\u200cشود و متنِ کد تا پیش از دریافت نشان داده نمی\u200cشود. با دریافت، کد به «کدهای من» همان کاربر می\u200cآید. فقط برای مخاطب «همه\u200cی کاربران».', verbose_name='کاربر بتواند در پنل «دریافت» کند'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_loyalty_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'همه (بدون محدودیت سطح)'), (1, 'سطح «برنزی» و بالاتر'), (2, 'سطح «نقره\u200cای» و بالاتر'), (3, 'سطح «طلایی» و بالاتر'), (4, 'سطح «الماسی» و بالاتر')], default=0, help_text='هم برای دریافت کد در پنل و هم برای استفاده از آن. ۰ = بدون محدودیت.', verbose_name='حداقل سطح وفاداری'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='terms',
            field=models.TextField(blank=True, default='', help_text='هر خط یک بند؛ در پنجره\u200cی «قوانین» کنار شرط\u200cهای خودکار (حداقل سبد، بازه\u200cی اعتبار و ...) نمایش داده می\u200cشود.', verbose_name='قوانین و توضیح برای کاربر'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.CharField(help_text='نامِ نمایشی برای کاربر (پنل و پنجره\u200cی قوانین). برای کدهای «قابل\u200cدریافت» متن خودِ کد را در عنوان ننویسید؛ کد تا قبل از دریافت به کاربر نشان داده نمی\u200cشود.', max_length=200, verbose_name='عنوان'),
        ),
    ]
