# Generated by Django 5.2.15 on 2026-09-26 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_coupon_snapshot'),
        ('payments', '0001_initial'),
        ('wallet', '0002_withdrawalrequest_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='سهم کیف\u200cپول'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بازگشت سهم کیف\u200cپول'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.wallettransaction', verbose_name='ردیف لجر کیف\u200cپول'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('wallet_amount__gte', 0)), name='transaction_wallet_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('wallet_reversed_at__isnull', False), _negated=True), ('wallet_amount__gt', 0), _connector='OR'), name='transaction_reversed_requires_wallet_amount'),
        ),
    ]
