# Generated by Django 5.2.15 on 2026-09-27 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.PositiveIntegerField(default=0, verbose_name='موجودی فعلی امتیاز')),
                ('lifetime_earned', models.PositiveIntegerField(default=0, help_text='با خرج\u200cکردن/کسر کاهش نمی\u200cیابد؛ فقط با کسب امتیاز جدید افزایش می\u200cیابد.', verbose_name='مجموع امتیاز کسب\u200cشده (کل تاریخچه)')),
                ('lifetime_redeemed', models.PositiveIntegerField(default=0, verbose_name='مجموع امتیاز خرج\u200cشده (کل تاریخچه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_account', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حساب باشگاه مشتریان',
                'verbose_name_plural': 'حساب\u200cهای باشگاه مشتریان',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مقدار (علامت\u200cدار: مثبت=کسب/واریز، منفی=خرج/کسر)')),
                ('balance_after', models.PositiveIntegerField(verbose_name='موجودی پس از این تراکنش')),
                ('transaction_type', models.CharField(choices=[('EARN_ORDER', 'کسب از خرید'), ('EARN_ACTION', 'کسب از سایر فعالیت\u200cها'), ('ADMIN_CREDIT', 'اعطای دستی توسط مدیر'), ('ADMIN_DEBIT', 'کسر دستی توسط مدیر'), ('REDEEM_WALLET', 'تبدیل به کیف پول'), ('REDEEM_REWARD', 'خرید پاداش/کوپن'), ('REVERSE', 'برگشت امتیاز (لغو/مرجوعی)'), ('EXPIRE', 'انقضای امتیاز')], max_length=15, verbose_name='نوع تراکنش')),
                ('source_type', models.CharField(blank=True, default='', max_length=50, verbose_name='نوع منبع')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه\u200cی منبع')),
                ('idempotency_key', models.CharField(blank=True, help_text='برای تراکنش\u200cهای سیستمی (نه دستیِ ادمین)؛ جلوگیری از ثبت دوباره\u200cی یک رویداد.', max_length=128, null=True, unique=True, verbose_name='کلید ضدتکرار')),
                ('expires_at', models.DateTimeField(blank=True, help_text='آمادگی معماری برای انقضای دوره\u200cای/FIFO در فازهای بعدی؛ در Phase 1 ذخیره می\u200cشود ولی هیچ\u200cجا اجرا نمی\u200cشود.', null=True, verbose_name='زمان انقضا')),
                ('remaining_amount', models.PositiveIntegerField(default=0, help_text='فقط برای تراکنش\u200cهای کسبِ مثبت (Earn) معنا دارد؛ برای پشتیبانی از کسر FIFO در فازهای بعدی.', verbose_name='باقی\u200cمانده\u200cی قابل\u200cمصرف')),
                ('reason', models.CharField(max_length=255, verbose_name='علت تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='loyalty.loyaltyaccount', verbose_name='حساب باشگاه')),
                ('created_by', models.ForeignKey(blank=True, help_text='برای تراکنش\u200cهای دستی: ادمین عامل. برای تراکنش\u200cهای سیستمی: خالی.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'تراکنش باشگاه مشتریان',
                'verbose_name_plural': 'تراکنش\u200cهای باشگاه مشتریان',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='loyaltyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('current_balance__gte', 0)), name='loyaltyaccount_current_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='loyaltytransaction_balance_after_gte_0'),
        ),
    ]
