# Generated by Django 5.2.15 on 2026-09-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='نام سطح')),
                ('rank', models.PositiveSmallIntegerField(unique=True, verbose_name='رتبه سطح')),
                ('threshold', models.PositiveIntegerField(unique=True, verbose_name='حداقل امتیاز کسب\u200cشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('badge_color', models.CharField(blank=True, default='', max_length=20, verbose_name='رنگ نشان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'سطح باشگاه مشتریان',
                'verbose_name_plural': 'سطوح باشگاه مشتریان',
                'ordering': ('rank',),
                'indexes': [models.Index(fields=['is_active', 'threshold'], name='loyaltytier_active_idx')],
            },
        ),
    ]
