# Generated by Django 5.2.15 on 2026-09-28 09:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_seed_loyalty_tiers'),
        ('promotions', '0005_claimable_coupons_and_shipping_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان پاداش در کاتالوگ')),
                ('points_cost', models.PositiveIntegerField(help_text='تعداد امتیازی که برای دریافت این پاداش از حساب کاربر کسر می\u200cشود.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='هزینه\u200cی امتیازی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (قابل بازخرید)')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='اولویت نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('coupon', models.OneToOneField(help_text='کوپنی که با خرج امتیاز به کاربر تخصیص می\u200cیابد. باید مخاطب «فقط کاربران تعریف\u200cشده» و غیرِ«قابل\u200cدریافت در پنل» باشد.', on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_reward', to='promotions.coupon', verbose_name='کد تخفیف مرتبط')),
            ],
            options={
                'verbose_name': 'پاداش باشگاه مشتریان',
                'verbose_name_plural': 'پاداش\u200cهای باشگاه مشتریان',
                'ordering': ('display_order', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('points_cost__gte', 1)), name='loyaltyreward_points_cost_gte_1')],
            },
        ),
    ]
