# Generated by Django 5.2.15 on 2026-09-29 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_loyaltyreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytier',
            name='legacy_equivalent_index',
            field=models.PositiveSmallIntegerField(blank=True, help_text='معادل این سطح در مقیاس ۵\u200cسطحی سنتی جهت انطباق با قوانین تخفیف و کوپن\u200cها. در صورت خالی بودن، فاقد معادل لحاظ می\u200cشود.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='اندیس معادل سنتی (۰ تا ۴)'),
        ),
    ]
