# Generated by Django 5.2.15 on 2026-09-29 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_loyaltytier_legacy_equivalent_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTierHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارتقا')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال اعلان')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tier_history', to='loyalty.loyaltyaccount', verbose_name='حساب وفاداری')),
                ('new_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loyalty.loyaltytier', verbose_name='سطح جدید')),
                ('old_tier', models.ForeignKey(blank=True, help_text='خالی یعنی این اولین سطحی است که کاربر تا امروز به آن رسیده.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loyalty.loyaltytier', verbose_name='سطح قبلی')),
                ('triggering_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loyalty.loyaltytransaction', verbose_name='تراکنش محرک')),
            ],
            options={
                'verbose_name': 'تاریخچه ارتقای رتبه وفاداری',
                'verbose_name_plural': 'تاریخچه ارتقای رتبه\u200cهای وفاداری',
                'ordering': ['-created_at'],
            },
        ),
    ]
