# Generated by Django 5.2.15 on 2026-09-27 06:49

import django.core.validators
import django.db.models.deletion
import returns.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_userbankaccount'),
        ('orders', '0012_order_delivered_at'),
        ('products', '0027_sitesettings_login_badge_icon_and_more'),
        ('wallet', '0002_withdrawalrequest_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('shipping_cost_payer', models.CharField(choices=[('customer', 'مشتری'), ('store', 'فروشگاه')], default='customer', max_length=10, verbose_name='پرداخت\u200cکننده\u200cی هزینه\u200cی پست برگشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (در فرم نمایش داده شود)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دلیل مرجوعی',
                'verbose_name_plural': 'دلایل مرجوعی',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReturnabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('product', 'محصولات مشخص'), ('category', 'دسته\u200cبندی (شامل زیردسته\u200cها)')], max_length=10, verbose_name='شمول قاعده')),
                ('reason_text', models.CharField(help_text='مثلاً «این کالا به دلیل بهداشتی قابل مرجوع نیست».', max_length=300, verbose_name='متن نمایش به کاربر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('categories', models.ManyToManyField(blank=True, help_text='شامل همه\u200cی زیردسته\u200cها.', related_name='+', to='products.category', verbose_name='دسته\u200cهای مشمول')),
                ('products', models.ManyToManyField(blank=True, related_name='+', to='products.product', verbose_name='محصولات مشمول')),
            ],
            options={
                'verbose_name': 'قاعده\u200cی عدم امکان مرجوعی',
                'verbose_name_plural': 'قواعد عدم امکان مرجوعی',
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField(verbose_name='تعداد درخواستی')),
                ('approved_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد تأییدشده پس از بازرسی')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=0, help_text='بر مبنای approved_quantity محاسبه می\u200cشود (نگاه کنید returns.refund_calculator - بخش دوم).', max_digits=12, null=True, verbose_name='مبلغ ریفاند این قلم')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات مشتری')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem', verbose_name='قلم سفارش')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='returns.returnreason', verbose_name='دلیل مرجوعی')),
            ],
            options={
                'verbose_name': 'قلم مرجوعی',
                'verbose_name_plural': 'اقلام مرجوعی',
            },
        ),
        migrations.CreateModel(
            name='ReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=returns.models._return_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'mp4', 'webm', 'mov'])], verbose_name='فایل')),
                ('attachment_type', models.CharField(choices=[('image', 'عکس'), ('video', 'فیلم')], max_length=10, verbose_name='نوع فایل')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='نام اصلی فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
                ('return_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='returns.returnitem', verbose_name='قلم مرجوعی')),
            ],
            options={
                'verbose_name': 'مدرک مرجوعی',
                'verbose_name_plural': 'مدارک مرجوعی',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تأییدشده (در انتظار ارسال کالا توسط مشتری)'), ('ITEM_RECEIVED', 'کالا دریافت شد (در انتظار بازرسی نهایی)'), ('REFUND_PENDING', 'در صف بازپرداخت'), ('COMPLETED', 'بازپرداخت تکمیل شد'), ('REJECTED', 'رد شد')], default='PENDING', max_length=15, verbose_name='وضعیت')),
                ('refund_method', models.CharField(choices=[('wallet', 'شارژ کیف\u200cپول'), ('bank', 'واریز دستی به حساب بانکی')], max_length=10, verbose_name='روش بازپرداخت')),
                ('bank_account_holder_snapshot', models.CharField(blank=True, max_length=100, verbose_name='نام صاحب حساب (اسنپ\u200cشات)')),
                ('bank_card_snapshot', models.CharField(blank=True, max_length=16, verbose_name='شماره کارت (اسنپ\u200cشات)')),
                ('bank_iban_snapshot', models.CharField(blank=True, max_length=26, verbose_name='شماره شبا (اسنپ\u200cشات)')),
                ('holoo_return_note', models.CharField(blank=True, help_text='فقط برای ردیابی دستی حسابداری؛ سایت هیچ سندی در هلو ثبت نمی\u200cکند.', max_length=200, verbose_name='یادداشت سند برگشت\u200cازفروش هلو')),
                ('shipping_refunded', models.BooleanField(default=False, verbose_name='هزینه\u200cی ارسال هم بازگردانده شد')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت درخواست')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصمیم (تأیید/رد)')),
                ('item_received_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان دریافت کالا')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل بازپرداخت')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.userbankaccount', verbose_name='حساب بانکی انتخاب\u200cشده (در لحظه\u200cی ثبت)')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده\u200cی تکمیل بازپرداخت')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تصمیم\u200cگیرنده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.order', verbose_name='سفارش')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده\u200cی دریافت کالا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('wallet_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_request', to='wallet.wallettransaction', verbose_name='تراکنش شارژ کیف\u200cپول ثبت\u200cشده')),
            ],
            options={
                'verbose_name': 'درخواست مرجوعی',
                'verbose_name_plural': 'درخواست\u200cهای مرجوعی',
                'ordering': ('-requested_at',),
            },
        ),
        migrations.AddField(
            model_name='returnitem',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest', verbose_name='درخواست مرجوعی'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='returnrequest_rejected_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('refund_method', 'bank'), _negated=True), ('bank_card_snapshot__gt', ''), ('bank_iban_snapshot__gt', ''), _connector='OR'), name='returnrequest_bank_refund_requires_account'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='returnrequest_completed_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gt', 0)), name='returnitem_requested_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('approved_quantity__isnull', True), ('approved_quantity__lte', models.F('requested_quantity')), _connector='OR'), name='returnitem_approved_lte_requested'),
        ),
    ]
