# Generated by Django 5.2.15 on 2026-09-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='shipping_refund_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ کرایه\u200cی مسترد\u200cشده'),
        ),
    ]
