# Generated by Django 5.2.15 on 2026-09-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_returnrequest_shipping_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnreason',
            name='requires_description',
            field=models.BooleanField(default=False, help_text='مثلاً برای دلیل «سایر»؛ روشن باشد یعنی مشتری باید حتماً توضیح بنویسد.', verbose_name='توضیح برای این دلیل اجباری باشد'),
        ),
    ]
