# Generated by Django 5.2.15 on 2026-10-07 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه\u200cی عمومی')),
                ('visitor_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='هش کوکی بازدیدکننده')),
                ('guest_name', models.CharField(blank=True, default='', max_length=80, verbose_name='نام (مهمان)')),
                ('guest_phone', models.CharField(blank=True, default='', max_length=11, verbose_name='موبایل (مهمان؛ فقط داده\u200cی کمکی)')),
                ('guest_phone_verified', models.BooleanField(default=False, verbose_name='موبایل مهمان تأیید شده')),
                ('channel_origin', models.CharField(choices=[('live', 'گفتگوی زنده'), ('offline', 'پیام آفلاین')], default='offline', max_length=8, verbose_name='کانال شروع')),
                ('status', models.CharField(choices=[('waiting_operator', 'در انتظار کارشناس'), ('active', 'در جریان'), ('waiting_customer', 'در انتظار مشتری'), ('offline', 'آفلاین (ناهمزمان)'), ('closed', 'بسته')], default='offline', max_length=16, verbose_name='وضعیت')),
                ('last_message_seq', models.PositiveIntegerField(default=0, verbose_name='آخرین شماره\u200cی پیام')),
                ('last_read_seq_by_customer', models.PositiveIntegerField(default=0, verbose_name='خوانده\u200cشده توسط مشتری تا')),
                ('last_read_seq_by_operator', models.PositiveIntegerField(default=0, verbose_name='خوانده\u200cشده توسط کارشناس تا')),
                ('unread_for_operator', models.PositiveIntegerField(default=0, verbose_name='خوانده\u200cنشده برای کارشناس')),
                ('unread_for_customer', models.PositiveIntegerField(default=0, verbose_name='خوانده\u200cنشده برای مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین پیام')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین فعالیت')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بسته شدن')),
                ('next_timer_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='موعد تایمر بعدی')),
                ('next_timer_kind', models.CharField(blank=True, default='', max_length=16, verbose_name='نوع تایمر')),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=140, verbose_name='پیش\u200cنمایش آخرین پیام')),
                ('last_message_sender', models.CharField(blank=True, default='', max_length=10, verbose_name='فرستنده\u200cی آخرین پیام')),
                ('source_path', models.CharField(blank=True, default='', max_length=300, verbose_name='صفحه\u200cی شروع')),
                ('client_ip_trunc', models.CharField(blank=True, default='', max_length=45, verbose_name='IP کوتاه\u200cشده')),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_assigned', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس مسئول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گفتگو',
                'verbose_name_plural': 'گفتگوها',
                'ordering': ('-last_message_at', '-id'),
                'permissions': (('operate_chat', 'می\u200cتواند گفتگوهای پشتیبانی را ببیند و پاسخ دهد'),),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='شماره\u200cی ترتیبی در گفتگو')),
                ('sender_type', models.CharField(choices=[('customer', 'مشتری'), ('operator', 'کارشناس'), ('system', 'سیستم')], max_length=10, verbose_name='فرستنده')),
                ('body', models.TextField(verbose_name='متن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('client_msg_id', models.UUIDField(default=uuid.uuid4, verbose_name='شناسه\u200cی سمت کلاینت (ضد تکرار)')),
                ('is_internal_note', models.BooleanField(default=False, verbose_name='یادداشت داخلی (فقط کارشناسان)')),
                ('kind', models.CharField(default='text', max_length=8, verbose_name='نوع')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='گفتگو')),
            ],
            options={
                'verbose_name': 'پیام گفتگو',
                'verbose_name_plural': 'پیام\u200cهای گفتگو',
                'ordering': ('conversation_id', 'seq'),
            },
        ),
        migrations.CreateModel(
            name='ChatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='نوع رخداد')),
                ('actor_type', models.CharField(max_length=10, verbose_name='عامل')),
                ('actor_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه\u200cی عامل')),
                ('from_status', models.CharField(blank=True, default='', max_length=16, verbose_name='از وضعیت')),
                ('to_status', models.CharField(blank=True, default='', max_length=16, verbose_name='به وضعیت')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='جزئیات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chat.conversation', verbose_name='گفتگو')),
            ],
            options={
                'verbose_name': 'رخداد گفتگو',
                'verbose_name_plural': 'رخدادهای گفتگو',
                'ordering': ('conversation_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OperatorPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, verbose_name='خود را آنلاین اعلام کرده')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='آخرین نبض')),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_presence', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
            ],
            options={
                'verbose_name': 'حضور کارشناس',
                'verbose_name_plural': 'حضور کارشناسان',
            },
        ),
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('body', models.TextField(help_text='می\u200cتوانید {customer_name} بنویسید؛ هنگام استفاده با نام مشتری جایگزین می\u200cشود.', verbose_name='متن پاسخ')),
                ('shortcut', models.CharField(blank=True, default='', help_text='مثلاً «ship» (کارشناس در پاسخ\u200cگویی با تایپ / آن را پیدا می\u200cکند).', max_length=30, verbose_name='میان\u200cبر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('owner', models.ForeignKey(blank=True, help_text='خالی = پاسخ عمومی برای همه\u200cی کارشناسان؛ وگرنه فقط برای همین کارشناس.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'پاسخ آماده',
                'verbose_name_plural': 'پاسخ\u200cهای آماده',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', '-last_message_at'], name='chat_conv_status_last_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-last_message_at'], name='chat_conv_user_last_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['assigned_operator', 'status'], name='chat_conv_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'seq'), name='chat_msg_conv_seq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'client_msg_id'), name='chat_msg_conv_client_uniq'),
        ),
        migrations.AddIndex(
            model_name='chatevent',
            index=models.Index(fields=['conversation', 'id'], name='chat_event_conv_idx'),
        ),
    ]
