# Generated by Django 5.2.15 on 2026-10-07 06:33

import chat.models
import chat.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachments_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد پیوست\u200cها'),
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه\u200cی عمومی')),
                ('file', models.FileField(max_length=200, storage=chat.storage.ChatAttachmentStorage(), upload_to=chat.models.attachment_upload_to, verbose_name='فایل')),
                ('kind', models.CharField(choices=[('image', 'تصویر'), ('pdf', 'PDF')], max_length=8, verbose_name='نوع')),
                ('ext', models.CharField(max_length=5, verbose_name='پسوند (از نوع واقعی فایل)')),
                ('content_type', models.CharField(max_length=40, verbose_name='نوع محتوا (از بررسی بایت\u200cها)')),
                ('original_name', models.CharField(blank=True, default='', max_length=80, verbose_name='نام اصلی (فقط نمایش)')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='حجم (بایت)')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عرض')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ارتفاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'پیوست گفتگو',
                'verbose_name_plural': 'پیوست\u200cهای گفتگو',
                'ordering': ('message_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='هش کوکی بازدیدکننده')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='دلیل (فقط برای کارشناسان)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان مسدودسازی')),
                ('expires_at', models.DateTimeField(blank=True, help_text='خالی = دائمی', null=True, verbose_name='پایان مسدودیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مسدودکننده')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='chat.conversation', verbose_name='گفتگوی مبدأ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مسدودسازی گفتگو',
                'verbose_name_plural': 'مسدودسازی\u200cهای گفتگو',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['is_active', 'visitor_hash'], name='chat_block_active_vh_idx')],
            },
        ),
    ]
