# Generated by Django 5.2.8 on 2026-07-05 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تایید ادمین'), ('PROCESSING', 'در حال پردازش (هلو)'), ('APPROVED', 'تایید و ثبت شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=15, verbose_name='وضعیت')),
                ('erp_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='کد هلو')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش مجدد')),
                ('last_sync_error', models.TextField(blank=True, null=True, verbose_name='آخرین خطای ارتباط با هلو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی کارمند')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد تایید')),
                ('purpose', models.CharField(choices=[('LOGIN', 'ثبت\u200cنام / ورود'), ('RESET', 'بازیابی رمز')], default='LOGIN', max_length=10, verbose_name='هدف')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش اشتباه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ استفاده')),
            ],
            options={
                'verbose_name': 'درخواست کد یکبار مصرف',
                'verbose_name_plural': 'درخواست\u200cهای کد یکبار مصرف',
                'indexes': [models.Index(fields=['phone_number', 'created_at'], name='accounts_ot_phone_n_6e04f3_idx')],
            },
        ),
    ]
