# Generated by Django 5.2.8 on 2026-07-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('PENDING_PROFILE', 'نیازمند تکمیل اطلاعات'), ('PENDING_ERP_SYNC', 'در انتظار همگام\u200cسازی هلو'), ('ACTIVE', 'مشتری فعال'), ('REJECTED', 'حساب مسدود')], default='PENDING_PROFILE', max_length=20, verbose_name='وضعیت'),
        ),
    ]
