# Generated by Django 5.2.8 on 2026-07-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='price_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'قیمت فروش 1'), (2, 'قیمت فروش 2'), (3, 'قیمت فروش 3'), (4, 'قیمت فروش 4'), (5, 'قیمت فروش 5'), (6, 'قیمت فروش 6'), (7, 'قیمت فروش 7'), (8, 'قیمت فروش 8'), (9, 'قیمت فروش 9'), (10, 'قیمت فروش 10')], default=1, verbose_name='سطح قیمت پیش\u200cفرض'),
        ),
    ]
