# Generated by Django 5.2.8 on 2026-07-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_avatar_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_sub',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='شناسه گوگل'),
        ),
    ]
