# Generated by Django 5.2.15 on 2026-07-23 14:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_google_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=accounts.models.OverwriteStorage(), upload_to=accounts.models.avatar_upload_path, verbose_name='تصویر پروفایل'),
        ),
    ]
