# Generated by Django 5.2.15 on 2026-09-20 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_avatar'),
        ('locations', '0002_seed_divisions_and_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: منزل، محل کار', max_length=50, verbose_name='عنوان آدرس')),
                ('receiver_first_name', models.CharField(max_length=50, verbose_name='نام گیرنده')),
                ('receiver_last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی گیرنده')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='موبایل گیرنده')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('address', models.TextField(verbose_name='آدرس دقیق')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='locations.city', verbose_name='شهر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('zone', models.ForeignKey(blank=True, help_text='فقط برای شهرهایی که ناحیه\u200cی ارسال فعال دارند و در آن\u200cها اجباری است.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='locations.deliveryzone', verbose_name='ناحیه')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
                'ordering': ('-is_default', '-created_at', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user')],
            },
        ),
    ]
