# Generated by Django 5.2.15 on 2026-09-20 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_migrate_legacy_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
    ]
