# Generated by Django 5.2.15 on 2026-09-23 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_legacy_address_fields'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت تأیید تجاری'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام فروشگاه/شرکت'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_users', to=settings.AUTH_USER_MODEL, verbose_name='ردکننده'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل رد'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approval_status', 'APPROVED'), _negated=True), models.Q(('first_name__isnull', False), models.Q(('first_name', ''), _negated=True), ('last_name__isnull', False), models.Q(('last_name', ''), _negated=True), ('national_code__isnull', False), models.Q(('national_code', ''), _negated=True)), _connector='OR'), name='customuser_approved_requires_complete_profile'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approval_status', 'APPROVED'), _negated=True), models.Q(('price_level__gte', 1), ('price_level__lte', 10)), _connector='OR'), name='customuser_approved_requires_valid_price_level'),
        ),
    ]
