# Generated by Django 5.2.15 on 2026-09-27 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_backfill_existing_customer_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_first_name', models.CharField(max_length=50, verbose_name='نام صاحب حساب')),
                ('account_holder_last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی صاحب حساب')),
                ('card_number', models.CharField(blank=True, max_length=16, verbose_name='شماره کارت (۱۶ رقم)')),
                ('iban', models.CharField(blank=True, max_length=26, verbose_name='شماره شبا')),
                ('is_default', models.BooleanField(default=False, verbose_name='حساب پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
                'ordering': ('-is_default', '-created_at', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_bank_account_per_user'), models.CheckConstraint(condition=models.Q(('card_number__gt', ''), ('iban__gt', ''), _connector='OR'), name='bank_account_requires_card_or_iban')],
            },
        ),
    ]
