# Generated by Django 5.2.15 on 2026-10-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userbankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='holoo_bed_sarfasl',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='سرفصل بدهکار در هلو'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='holoo_customer_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='کد طرف\u200cحساب در هلو'),
        ),
    ]
