# Generated by Django 5.2.15 on 2026-10-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_holoo_real_integration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='holoo_full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='نام کامل در هلو'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='imported_from_holoo',
            field=models.BooleanField(default=False, verbose_name='مشتری قبلی هلو'),
        ),
    ]
