# Generated by Django 5.2.15 on 2026-10-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_holoo_imported_customer_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_purchase_with_check',
            field=models.BooleanField(default=False, help_text='با تأیید اعتباری توسط مدیر فعال می\u200cشود. مشتری نقدی با این مجوز گزینه\u200cی چکی (قیمت چکی) را می\u200cبیند؛ مشتری ویژه با همان قیمت اختصاصی ویژه\u200cاش چکی می\u200cخرد.', verbose_name='مجوز خرید چکی'),
        ),
    ]
