# Generated by Django 5.2.15 on 2026-10-08 06:01

import accounts.cheque_credit
import accounts.credit_storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_cheque_settlement_separation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeCreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه\u200cی عمومی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('canceled', 'انصراف مشتری')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('business_name', models.CharField(max_length=255, verbose_name='نام فروشگاه/شرکت')),
                ('bank_name', models.CharField(max_length=60, verbose_name='نام بانک')),
                ('account_holder', models.CharField(max_length=100, verbose_name='نام صاحب حساب')),
                ('iban', models.CharField(max_length=26, verbose_name='شماره شبا')),
                ('requested_limit', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='سقف اعتبار درخواستی (تومان)')),
                ('monthly_turnover', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='میانگین گردش/خرید ماهانه (تومان)')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='توضیحات مشتری')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('rejection_reason', models.CharField(blank=True, default='', help_text='برای رد الزامی است و به مشتری نمایش داده می\u200cشود.', max_length=300, verbose_name='علت رد')),
                ('approved_limit', models.DecimalField(blank=True, decimal_places=0, help_text='فعلاً فقط اطلاعاتی است و در تسویه\u200cحساب اعمال نمی\u200cشود.', max_digits=15, null=True, verbose_name='سقف اعتبار تأییدشده (تومان)')),
                ('admin_note', models.CharField(blank=True, default='', max_length=500, verbose_name='یادداشت داخلی مدیر')),
                ('decided_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان تعیین\u200cتکلیف')),
                ('documents_purged_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاک\u200cسازی مدارک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheque_credit_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست خرید چکی',
                'verbose_name_plural': 'درخواست\u200cهای خرید چکی',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ChequeCreditDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه\u200cی عمومی')),
                ('kind', models.CharField(choices=[('cheque_book', 'تصویر دسته\u200cچک'), ('national_card', 'کارت ملی'), ('business_license', 'مجوز کسب\u200cوکار'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع مدرک')),
                ('file', models.FileField(max_length=200, storage=accounts.credit_storage.ChequeCreditDocStorage(), upload_to=accounts.cheque_credit.cheque_credit_doc_upload_to, verbose_name='فایل')),
                ('ext', models.CharField(max_length=5, verbose_name='پسوند (از نوع واقعی فایل)')),
                ('content_type', models.CharField(max_length=40, verbose_name='نوع محتوا (از بررسی بایت\u200cها)')),
                ('original_name', models.CharField(blank=True, default='', max_length=80, verbose_name='نام اصلی (فقط نمایش)')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='حجم (بایت)')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عرض')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ارتفاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.chequecreditrequest', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'مدرک درخواست خرید چکی',
                'verbose_name_plural': 'مدارک درخواست خرید چکی',
                'ordering': ('request_id', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='chequecreditrequest',
            index=models.Index(fields=['status', 'created_at'], name='chq_credit_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='chequecreditrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='cheque_credit_one_pending_per_user'),
        ),
        migrations.AddConstraint(
            model_name='chequecreditrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), ('rejection_reason__gt', ''), _connector='OR'), name='cheque_credit_reject_needs_reason'),
        ),
        migrations.AddConstraint(
            model_name='chequecreditrequest',
            constraint=models.CheckConstraint(condition=models.Q(('requested_limit__gt', 0)), name='cheque_credit_requested_limit_gt_0'),
        ),
    ]
