# Generated by Django 5.2.15 on 2026-10-08 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_cheque_credit_request'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cheque_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='خالی = بدون سقف؛ عدد مثبت = حداکثر مجموع سفارش\u200cهای چکیِ تسویه\u200cنشده؛ ۰ = فریز (سفارش چکیِ جدید ممکن نیست).', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سقف اعتبار خرید چکی (تومان)'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('cheque_credit_limit__isnull', True), ('cheque_credit_limit__gte', 0), _connector='OR'), name='customuser_cheque_credit_limit_gte_0'),
        ),
    ]
