# Generated by Django 5.2.15 on 2026-07-18 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_product_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('published', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='خریدار تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.review', verbose_name='پاسخ به')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/', verbose_name='تصویر')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='نظر')),
            ],
            options={
                'verbose_name': 'تصویر نظر',
                'verbose_name_plural': 'تصاویر نظرات',
            },
        ),
        migrations.CreateModel(
            name='ReviewPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pro', 'مثبت'), ('con', 'منفی')], max_length=3, verbose_name='نوع')),
                ('text', models.CharField(max_length=200, verbose_name='متن')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='reviews.review', verbose_name='نظر')),
            ],
            options={
                'verbose_name': 'نقطه قوت/ضعف',
                'verbose_name_plural': 'نقاط قوت و ضعف',
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('product', 'user'), name='one_top_level_review_per_user_product'),
        ),
    ]
