# Generated by Django 5.2.15 on 2026-07-23 21:42

import reviews.models
import services.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewimage_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(storage=services.storage.OverwriteStorage(), upload_to=reviews.models.review_image_upload_path, verbose_name='تصویر'),
        ),
    ]
