"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--q1()f-7l8mz(66p1am85r)er7a!_2#j&#gipe(5@yo!!2^gj2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'locations.apps.LocationsConfig',
    'accounts.apps.AccountsConfig',
    'holoo.apps.HolooConfig',
    'products.apps.ProductsConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    'payments.apps.PaymentsConfig',
    'wishlist.apps.WishlistConfig',
    'recently_viewed.apps.RecentlyViewedConfig',
    'reviews.apps.ReviewsConfig',
    'compare.apps.CompareConfig',
    'blog.apps.BlogConfig',
    'notifications.apps.NotificationsConfig',
    'django_ckeditor_5',
    'django_cleanup.apps.CleanupConfig',  # باید آخر لیست باشد
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.storefront',
                'accounts.context_processors.login_captcha',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'HolooWebDB',
        'USER': 'sa',
        'PASSWORD': 'poolasa@123',
        'HOST': 'localhost',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes;Encrypt=yes',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# MinimumLengthValidator/NumericPasswordValidator پیش‌فرض جنگو با نسخه‌ی فارسی‌شده در
# accounts/password_validators.py جایگزین شده‌اند (دلیل و توضیحات کامل در همان فایل)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'accounts.password_validators.MinLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'accounts.password_validators.ContainsLetterValidator',
    },
    {
        'NAME': 'accounts.password_validators.ContainsDigitValidator',
    },
    {
        'NAME': 'accounts.password_validators.ContainsSymbolValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'  # برای پشتیبانی بهتر از فارسی در خطاهای پیش‌فرض

TIME_ZONE = 'Asia/Tehran' # تنظیم منطقه زمانی ایران

USE_I18N = True

# مسیر ترجمه‌های اختصاصی پروژه (برای رفع نواقص ترجمه فارسی جنگو مثل پیام‌های ادمین)
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'

# ==========================================
# اطلاع‌رسانی (پیامک / ایمیل / ...)
# ==========================================
# موتور فعال از تنظیمات سایت (SiteSettings.notification_backend، کمبوی ادمین) خوانده
# می‌شود تا تعویض سرویس نیاز به دیپلوی نداشته باشد. مقدار زیر فقط یک محافظ عقب‌افتاده است
# برای وقتی آن ردیف هنوز مقداردهی نشده. موتورهای آماده:
#   notifications.backends.console.ConsoleBackend     -> چاپ در ترمینال (توسعه)
#   notifications.backends.kavenegar.KavenegarBackend -> پیامک کاوه‌نگار
#   notifications.backends.melipayamak.MelipayamakBackend -> پیامک ملی‌پیامک (خط خدماتی اشتراکی)
#   notifications.backends.email.EmailBackend         -> ایمیل
NOTIFICATION_BACKEND = os.environ.get('NOTIFICATION_BACKEND', 'notifications.backends.console.ConsoleBackend')

# مقصد همه‌ی هشدارهای مدیر (شماره موبایل یا ایمیل، بسته به موتور فعال)
ADMIN_NOTIFICATION_RECIPIENT = os.environ.get('ADMIN_NOTIFICATION_RECIPIENT', '09192515466')

# تنظیمات موتور کاوه‌نگار (فقط وقتی موتور فعال روی کاوه‌نگار باشد استفاده می‌شود)
KAVENEGAR_API_KEY = os.environ.get('KAVENEGAR_API_KEY', '')
KAVENEGAR_SENDER = os.environ.get('KAVENEGAR_SENDER', '')

# تنظیمات موتور ملی‌پیامک (فقط وقتی موتور فعال روی ملی‌پیامک باشد استفاده می‌شود)
# username هنوز پر نشده — از داخل پنل ملی‌پیامک (نام کاربری حساب) بگیر و همین‌جا/در محیط
# اجرا مقداردهی کن. apikey طبق راهنمای ملی‌پیامک به‌جای رمز عبور در وب‌سرویس فرستاده می‌شود؛
# مقدار فعلی موقتی است (به گفته‌ی کارفرما بعداً به‌جای امن‌تری منتقل و عوض می‌شود).
MELIPAYAMAK_USERNAME = os.environ.get('MELIPAYAMAK_USERNAME', '29127540293')
MELIPAYAMAK_APIKEY = os.environ.get('MELIPAYAMAK_APIKEY', '49dca9b7-8849-4689-aa91-559d22fc43ba')
# شماره خط اختصاصی (SmartSMS) برای پیام‌های متن‌آزاد (مثل هشدار بحرانی سیستم) که روی خط
# خدماتی اشتراکی الگوی تاییدشده ندارند
MELIPAYAMAK_FROM_NUMBER = os.environ.get('MELIPAYAMAK_FROM_NUMBER', '50002710040293')

# ==========================================
# Celery & Redis Settings
# ==========================================
# REDIS_URL = os.environ.get('REDIS_URL', 'redis://192.168.1.3:6379')
REDIS_URL = os.environ.get('REDIS_URL', 'redis://192.168.0.100:6379')

CELERY_BROKER_URL = f'{REDIS_URL}/0'
CELERY_RESULT_BACKEND = f'{REDIS_URL}/0'

# ==========================================
# Cache
# ==========================================
# کش *باید* مشترک بین پروسه‌ها باشد (نه LocMemCache پیش‌فرض جنگو)، چون علاوه بر کش معمولی،
# قفل‌های توزیع‌شده‌ی تسک‌ها هم روی همین backend کار می‌کنند: قفل سینک محصولات هلو و قفل
# جلوگیری از ثبت فاکتور/سند تکراری. با کش درون‌پروسه‌ای، دو Worker همدیگر را نمی‌بینند و
# قفل بی‌اثر می‌شود.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'{REDIS_URL}/1',
        'KEY_PREFIX': 'holoo_web',
    }
}

# تنظیمات کالیبره شده برای فرمت دیتا
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tehran'

# زمان‌بندی تسک‌های دوره‌ای (نیازمند اجرای جداگانه‌ی `celery -A config beat`)
CELERY_BEAT_SCHEDULE = {
    'sync-products-from-holoo': {
        'task': 'holoo.tasks.sync_products_from_holoo',
        'schedule': 1500.0,  # هر ۲۵ دقیقه
    },
    # تور ایمنی: سفارش‌هایی که فاکتور یا سند دریافت وجه‌شان در چرخه‌ی عادی از قلم افتاده
    # (مثلاً Redis لحظه‌ی شلیک پایین بوده یا Worker وسط کار کشته شده) را دوباره به صف می‌فرستد.
    # هر دو تسک مقصد idempotent‌اند، پس اجرای تکراری بی‌خطر است.
    'reconcile-holoo-orders': {
        'task': 'holoo.tasks.reconcile_holoo_orders',
        'schedule': 900.0,  # هر ۱۵ دقیقه
    },
    # پیام‌هایی که تسکشان اصلاً شلیک نشده (مثلاً Redis لحظه‌ی ثبت پایین بوده) را برمی‌دارد
    'retry-pending-notifications': {
        'task': 'notifications.tasks.retry_pending_notifications',
        'schedule': 600.0,  # هر ۱۰ دقیقه
    },
}

# ==========================================
# Media Files Settings
# ==========================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==========================================
# CKEditor 5 (ویرایشگر متنی برای «توضیحات تکمیلی» محصول)
# ==========================================
CKEDITOR_5_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'fontColor', 'fontBackgroundColor', '|',
            'alignment', 'bulletedList', 'numberedList', '|',
            'link', 'insertImage', 'insertTable', 'blockQuote', '|',
            'undo', 'redo',
        ],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight'],
            'styles': ['full', 'alignLeft', 'alignCenter', 'alignRight'],
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells'],
        },
    },
}

# تنظیمات اتصال به API هلو
HOLOO_API_BASE_URL = "http://your-holoo-server-ip:port" # در فاز نهایی با آدرس سرور هلو جایگزین می‌شود
HOLOO_API_KEY = "your_secret_api_key_here" # در فاز نهایی با کلید دریافتی جایگزین می‌شود

# تنظیمات لاگین وب‌سرویس هلو (برای HolooClient.login / get_products / ...)
# پیش‌فرض‌ها مقادیر Mock/تست هستند؛ برای اتصال واقعی این‌ها را در محیط (env var) ست کنید.
HOLOO_API_URL = os.environ.get('HOLOO_API_URL', 'http://185.176.35.187:8080/TncHoloo/api')
HOLOO_MOCK_MODE = os.environ.get('HOLOO_MOCK_MODE', 'True') == 'True'
HOLOO_USERNAME = os.environ.get('HOLOO_USERNAME', 'web')
# مقدار همون چیزیه که مستقیم توی فیلد userpass وارد می‌شه (از قبل base64 شده، دقیقاً مثل چیزی که در Swagger می‌زنید)
HOLOO_PASSWORD = os.environ.get('HOLOO_PASSWORD', 'MQ==')
HOLOO_DB_NAME = os.environ.get('HOLOO_DB_NAME', 'Holoo1')
HOLOO_LOGIN_AUTH_HEADER = os.environ.get('HOLOO_LOGIN_AUTH_HEADER', '123')  # هدر Authorization دلخواه فقط برای /Login

# پرچم مجزا برای «فقط خواندن کالا» (login/get_products/get_product_count).
# چون ثبت‌نام مشتری/فاکتور هنوز طبق مستندات واقعی هلو تأیید نشده، HOLOO_MOCK_MODE عمومی
# فعلاً True می‌ماند و آن مسیرها را مجزا محافظت می‌کند؛ ولی خواندن کالا از سرور واقعی
# تست و تأیید شده (سینک کامل ۵۹۷۳ کالا با موفقیت انجام شد)، پس پیش‌فرض این پرچم False
# (واقعی) است. اگر لازم شد موقتاً به Mock برگردید، HOLOO_PRODUCTS_MOCK_MODE=True ست کنید.
HOLOO_PRODUCTS_MOCK_MODE = os.environ.get('HOLOO_PRODUCTS_MOCK_MODE', 'False') == 'True'

# تنظیمات ورود با گوگل (OAuth2 مستقیم، بدون پکیج اضافه).
# GOOGLE_CLIENT_ID/GOOGLE_CLIENT_SECRET را باید از Google Cloud Console (OAuth Client ID از نوع Web application) بگیرید
# و از طریق متغیر محیطی ست کنید؛ Authorized redirect URI باید دقیقاً برابر GOOGLE_REDIRECT_URI باشد.
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
GOOGLE_REDIRECT_URI = os.environ.get('GOOGLE_REDIRECT_URI', 'http://localhost:8010/accounts/google/callback/')

# ==========================================
# Logging
# ==========================================
# تا پیش از این هیچ پیکربندی لاگی وجود نداشت؛ یعنی logger.critical‌های مسیرهای بحرانی
# (ثبت‌نشدن فاکتور در هلو، ناهماهنگی مبلغ پرداخت، شکست ارسال پیام) فقط در کنسول ظاهر
# می‌شدند و روی سرور عملاً گم بودند. حالا سه مقصد دارند: کنسول، فایل چرخشی، و پیام به مدیر.
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}:{lineno} — {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',
        },
        # encoding صریح لازم است: پیام‌های لاگ این پروژه فارسی‌اند و روی ویندوز، هندلر
        # فایل بدون این تنظیم با کدپیج سیستم می‌نویسد و خروجی ناخوانا می‌شود
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'app.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'encoding': 'utf-8',
            'formatter': 'verbose',
            'level': 'INFO',
        },
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'encoding': 'utf-8',
            'formatter': 'verbose',
            'level': 'ERROR',
        },
        # فقط CRITICAL: مواردی که واقعاً نیاز به دخالت انسان دارند
        'admin_alert': {
            'class': 'config.logging_handlers.AdminAlertHandler',
            'formatter': 'simple',
            'level': 'CRITICAL',
        },
    },
    'root': {
        'handlers': ['console', 'file', 'error_file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # نویز درخواست‌های ۴۰۴/۵۰۰ توسعه در کنسول لازم نیست دوباره در فایل هم بیاید
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # اپ‌هایی که مسیر پول/حسابداری را لمس می‌کنند، هشدار بحرانی‌شان به مدیر هم می‌رسد
        'holoo': {
            'handlers': ['console', 'file', 'error_file', 'admin_alert'],
            'level': 'INFO',
            'propagate': False,
        },
        'payments': {
            'handlers': ['console', 'file', 'error_file', 'admin_alert'],
            'level': 'INFO',
            'propagate': False,
        },
        'orders': {
            'handlers': ['console', 'file', 'error_file', 'admin_alert'],
            'level': 'INFO',
            'propagate': False,
        },
        # عمداً بدون admin_alert (ضدحلقه: شکست ارسال پیام نباید ارسال پیام تازه بسازد)
        'notifications': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
