# Generated by Django 5.2.15 on 2026-09-26 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی کل')),
                ('reserved_balance', models.DecimalField(decimal_places=0, default=0, help_text='مبالغ درخواست\u200cهای برداشت PENDING؛ تا تصمیم نهایی از available_balance کم است ولی از balance کم نشده.', max_digits=12, verbose_name='موجودی بلوکه\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (علامت\u200cدار: مثبت=واریز، منفی=برداشت)')),
                ('kind', models.CharField(choices=[('topup', 'شارژ کیف پول'), ('withdrawal', 'برداشت / تسویه'), ('refund', 'مرجوعی فاکتور'), ('loyalty_redeem', 'تبدیل امتیاز وفاداری'), ('cart_payment', 'پرداخت سبد خرید با کیف پول'), ('reversal', 'تراکنش اصلاحی معکوس')], max_length=20, verbose_name='نوع تراکنش')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='موجودی پس از این تراکنش')),
                ('reference_type', models.CharField(blank=True, default='', max_length=50, verbose_name='نوع مرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه\u200cی مرجع')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(blank=True, help_text='کاربر خودش (شارژ/پرداخت) یا ادمین (تسویه\u200cی دستی/اصلاح).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WalletTopupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ درخواستی')),
                ('authority', models.CharField(max_length=100, unique=True, verbose_name='کد ارجاع درگاه (Authority)')),
                ('ref_id', models.CharField(blank=True, default='', max_length=100, verbose_name='شماره پیگیری بانک (RefID)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_requests', to='wallet.wallet', verbose_name='کیف پول')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topup_request', to='wallet.wallettransaction', verbose_name='تراکنش شارژ ثبت\u200cشده')),
            ],
            options={
                'verbose_name': 'درخواست شارژ کیف پول',
                'verbose_name_plural': 'درخواست\u200cهای شارژ کیف پول',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ درخواستی')),
                ('card_number_snapshot', models.CharField(blank=True, default='', max_length=25, verbose_name='شماره کارت (اسنپ\u200cشات)')),
                ('iban_snapshot', models.CharField(blank=True, default='', max_length=34, verbose_name='شماره شبا (اسنپ\u200cشات)')),
                ('account_holder_snapshot', models.CharField(max_length=100, verbose_name='نام صاحب حساب (اسنپ\u200cشات)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('COMPLETED', 'تسویه شد'), ('REJECTED', 'رد شد')], default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='دلیل رد')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصمیم\u200cگیری')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تصمیم\u200cگیرنده')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_request', to='wallet.wallettransaction', verbose_name='تراکنش برداشت ثبت\u200cشده')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'درخواست برداشت',
                'verbose_name_plural': 'درخواست\u200cهای برداشت',
                'ordering': ('-requested_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_balance__gte', 0)), name='wallet_reserved_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_balance__lte', models.F('balance'))), name='wallet_reserved_lte_balance'),
        ),
        migrations.AddConstraint(
            model_name='wallettopuprequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='wallettopuprequest_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='wallettopuprequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'success'), _negated=True), ('transaction__isnull', False), _connector='OR'), name='wallettopuprequest_success_requires_transaction'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='withdrawalrequest_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='withdrawalrequest_rejected_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('transaction__isnull', False), _connector='OR'), name='withdrawalrequest_completed_requires_transaction'),
        ),
    ]
