# Generated by Django 5.2.15 on 2026-09-26 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان واریز نهایی'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تأییدشده (در صف واریز دستی)'), ('COMPLETED', 'تسویه شد'), ('REJECTED', 'رد شد')], default='PENDING', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='withdrawalrequest_completed_requires_paid_at'),
        ),
    ]
