# Generated by Django 5.2.15 on 2026-07-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_color'),
        ('products', '0006_fix_additional_description_collation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'color')},
        ),
    ]
