# Generated by Django 5.2.15 on 2026-09-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام استان')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
                ('is_active', models.BooleanField(default=True, help_text='شهر غیرفعال در فرم ثبت آدرس نمایش داده نمی\u200cشود (آدرس\u200cهای قبلی دست نمی\u200cخورند).', verbose_name='فعال')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='locations.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ('province__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ناحیه')),
                ('shipping_cost', models.PositiveIntegerField(default=0, help_text='۰ یعنی «تعرفه تنظیم\u200cنشده»؛ تا وقتی عدد بیشتر از صفر نگذاشته\u200cاید این ناحیه در هیچ محاسبه\u200cای شرکت نمی\u200cکند.', verbose_name='کرایه\u200cی پیک (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='locations.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'ناحیه\u200cی ارسال',
                'verbose_name_plural': 'نواحی ارسال',
                'ordering': ('city__name', 'sort_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('city', 'name'), name='unique_zone_name_per_city')],
            },
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='unique_city_name_per_province'),
        ),
    ]
