# Generated by Django 5.2.8 on 2026-07-13 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_price10_product_price2_product_price3_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام گیرنده')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی گیرنده')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس گیرنده')),
                ('address', models.TextField(verbose_name='آدرس کامل')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی (قیمت 1)'), ('check', 'چکی (قیمت 2)'), ('installment', 'اقساطی (قیمت 3)')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه ارسال')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ کل سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید/پرداخت'), ('processing', 'در حال پردازش (ارسال به هلو)'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('holoo_preinvoice_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پیش\u200cفاکتور در هلو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت ثبت شده')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
