# Generated by Django 5.2.15 on 2026-07-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='holoo_preinvoice_id',
        ),
        migrations.AddField(
            model_name='order',
            name='holoo_invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره فاکتور در هلو'),
        ),
    ]
