# Generated by Django 5.2.8 on 2026-07-19 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_holoo_preinvoice_id_and_more'),
        ('products', '0005_brand_product_additional_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productcolor', verbose_name='رنگ خریداری\u200cشده'),
        ),
    ]
