# Generated by Django 5.2.15 on 2026-09-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_method_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='holoo_sync_alert_sent',
            field=models.BooleanField(default=False, verbose_name='هشدار تاخیر ثبت در هلو ارسال شد'),
        ),
    ]
