# Generated by Django 5.2.15 on 2026-09-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_holoo_sync_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='holoo_receipt_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره سند دریافت وجه در هلو'),
        ),
    ]
