# Generated by Django 5.2.15 on 2026-09-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_holoo_receipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد رهگیری پستی'),
        ),
    ]
