# Generated by Django 5.2.15 on 2026-09-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_label',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='برچسب ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('courier', 'ارسال با پیک'), ('post', 'ارسال با پست (پس\u200cکرایه)')], default='', max_length=10, verbose_name='روش ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='zone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ناحیه'),
        ),
    ]
