# Generated by Django 5.2.15 on 2026-09-20 13:25

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_shipping_snapshot'),
        ('products', '0021_delete_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='تخفیف سطح سفارش (کد تخفیف)'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_discount_label',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='عنوان تخفیف سطح سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='جمع تخفیف\u200cهای خودکار'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='تخفیف هر واحد'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='original_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت اصلی (قبل از تخفیف)'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('promotion_discount__gte', 0)), name='order_promotion_discount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('order_discount__gte', 0)), name='order_order_discount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='orderitem_discount_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('original_price', 0), ('original_price', django.db.models.expressions.CombinedExpression(models.F('price'), '+', models.F('discount_amount'))), _connector='OR'), name='orderitem_original_eq_price_plus_discount'),
        ),
    ]
