# Generated by Django 5.2.15 on 2026-09-20 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_discount_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='کرایه\u200cی بخشیده\u200cشده'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_discount__gte', 0)), name='order_shipping_discount_gte_0'),
        ),
    ]
