# Generated by Django 5.2.15 on 2026-10-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', help_text='اختیاری؛ در جزئیات سفارش به مشتری نشان داده می\u200cشود.', max_length=255, verbose_name='دلیل لغو'),
        ),
        migrations.AddField(
            model_name='order',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو'),
        ),
    ]
