# Generated by Django 5.2.15 on 2026-10-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_mark_legacy_orders_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='holoo_invoice_erp_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ErpCode فاکتور در هلو'),
        ),
        migrations.AddField(
            model_name='order',
            name='holoo_last_error',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='آخرین خطای هلو'),
        ),
        migrations.AddField(
            model_name='order',
            name='holoo_needs_attention',
            field=models.BooleanField(default=False, verbose_name='ثبت در هلو نیاز به بررسی دستی دارد'),
        ),
    ]
