# Generated by Django 5.2.15 on 2026-10-07 10:54

from django.db import migrations, models


def mark_existing_cheque_orders(apps, schema_editor):
    """
    قبل از جدا شدن «ستون قیمت» از «روش تسویه»، payment_method='check' هر دو معنا را داشت. این سفارش‌ها همگی تسویه‌ی چکی‌اند؛
    فقط فیلد تازه پر می‌شود (قیمت‌ها، ردیف‌ها و مبلغ‌ها دست‌نخورده‌اند). idempotent است. بازگشت (reverse) کاری نمی‌کند: فیلد
    settlement با حذف شدنش خودبه‌خود از بین می‌رود و payment_method='check' همچنان همان سفارش‌ها را نشان می‌دهد.
    """
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(payment_method='check').exclude(settlement='cheque').update(settlement='cheque')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_holoo_real_integration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='settlement',
            field=models.CharField(choices=[('online', 'پرداخت آنلاین/کیف\u200cپول'), ('cheque', 'چکی (تسویه\u200cی خارج از سایت)')], default='online', max_length=10, verbose_name='روش تسویه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('check', 'چکی (قیمت 1)'), ('cash', 'نقدی (قیمت 2)'), ('vip', 'ویژه (قیمت 3)')], default='cash', max_length=20, verbose_name='ستون قیمت (روش پرداخت)'),
        ),
        migrations.RunPython(mark_existing_cheque_orders, migrations.RunPython.noop),
    ]
