# Generated by Django 5.2.15 on 2026-10-07 11:44

import django.db.models.deletion
import orders.models
import orders.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_cheque_settlement_separation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه\u200cی عمومی')),
                ('sayadi_id', models.CharField(max_length=16, verbose_name='شناسه\u200cی صیادی (۱۶ رقم)')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='مبلغ چک (تومان)')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('bank_name', models.CharField(blank=True, default='', max_length=60, verbose_name='نام بانک')),
                ('holder_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام صاحب حساب')),
                ('status', models.CharField(choices=[('pending_review', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'ردشده')], db_index=True, default='pending_review', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'چک سفارش',
                'verbose_name_plural': 'چک\u200cهای سفارش',
                'ordering': ('order_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChequeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه\u200cی عمومی')),
                ('file', models.FileField(max_length=200, storage=orders.storage.ChequeImageStorage(), upload_to=orders.models.cheque_image_upload_to, verbose_name='فایل')),
                ('ext', models.CharField(max_length=5, verbose_name='پسوند (از نوع واقعی فایل)')),
                ('content_type', models.CharField(max_length=40, verbose_name='نوع محتوا (از بررسی بایت\u200cها)')),
                ('original_name', models.CharField(blank=True, default='', max_length=80, verbose_name='نام اصلی (فقط نمایش)')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='حجم (بایت)')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عرض')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ارتفاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.chequepayment', verbose_name='چک')),
            ],
            options={
                'verbose_name': 'تصویر چک',
                'verbose_name_plural': 'تصاویر چک',
                'ordering': ('cheque_id', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='chequepayment',
            constraint=models.UniqueConstraint(fields=('order', 'sayadi_id'), name='cheque_order_sayadi_uniq'),
        ),
    ]
