# Generated by Django 5.2.15 on 2026-10-07 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_cheque_payments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chequepayment',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='علت رد چک'),
        ),
        migrations.AddField(
            model_name='chequepayment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی'),
        ),
        migrations.AddField(
            model_name='chequepayment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='chequepayment',
            name='status',
            field=models.CharField(choices=[('pending_review', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'ردشده (نیاز به اصلاح)'), ('withdrawn', 'حذف\u200cشده توسط مشتری')], db_index=True, default='pending_review', max_length=20, verbose_name='وضعیت'),
        ),
    ]
