# Generated by Django 5.2.15 on 2026-10-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_cheque_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cheque_deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='مهلت ثبت اطلاعات چک'),
        ),
    ]
