# Generated by Django 5.2.15 on 2026-10-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_cheque_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequepayment',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت وصول'),
        ),
        migrations.AddField(
            model_name='order',
            name='cheque_settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان وصول کامل چک\u200cها'),
        ),
        migrations.AlterField(
            model_name='chequepayment',
            name='status',
            field=models.CharField(choices=[('pending_review', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'ردشده (نیاز به اصلاح)'), ('withdrawn', 'حذف\u200cشده توسط مشتری'), ('cleared', 'وصول\u200cشده')], db_index=True, default='pending_review', max_length=20, verbose_name='وضعیت'),
        ),
    ]
