# Generated by Django 5.2.15 on 2026-09-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(db_index=True, max_length=190, verbose_name='مقصد')),
                ('template_key', models.CharField(max_length=64, verbose_name='نوع پیام')),
                ('text', models.TextField(verbose_name='متن ارسالی')),
                ('status', models.CharField(choices=[('pending', 'در صف ارسال'), ('sent', 'ارسال شد'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('backend', models.CharField(blank=True, max_length=190, verbose_name='موتور ارسال')),
                ('provider_message_id', models.CharField(blank=True, max_length=190, verbose_name='شناسه نزد سرویس')),
                ('error', models.TextField(blank=True, verbose_name='آخرین خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'پیام خروجی',
                'verbose_name_plural': 'پیام\u200cهای خروجی',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx')],
            },
        ),
    ]
