# Generated by Django 5.2.15 on 2026-09-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='context',
            field=models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای قالب'),
        ),
    ]
