# Generated by Django 5.2.15 on 2026-09-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='backend_override',
            field=models.CharField(blank=True, max_length=190, verbose_name='بک\u200cاند اختصاصی این پیام'),
        ),
    ]
