# Generated by Django 5.2.15 on 2026-09-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_backend_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=64, unique=True, verbose_name='کلید قالب پیام')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='فعال (ارسال شود)')),
                ('custom_body', models.TextField(blank=True, help_text='اگر خالی باشد، متن پیش\u200cفرض تعریف\u200cشده در کد استفاده می\u200cشود. پارامترهای لازم قالب باید عیناً با همان نام (مثلاً {name}) در متن جای\u200cگزین هم باشند.', verbose_name='متن جای\u200cگزین')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'تنظیمات نوع پیام',
                'verbose_name_plural': 'تنظیمات انواع پیام',
                'ordering': ('template_key',),
            },
        ),
    ]
