# Generated by Django 5.2.8 on 2026-07-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductFeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مشخصات فنی محصولات',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_id_a08e3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_name_9ff0a3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='erp_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه گروه در هلو'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/', verbose_name='تصویر اصلی سایت'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='گروه پدر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='دسته\u200cبندی فرعی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات معرفی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='erp_code',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ErpCode هلو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نمایش در سایت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.FloatField(default=0, verbose_name='موجودی'),
        ),
        migrations.AddField(
            model_name='productfeaturevalue',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.feature', verbose_name='ویژگی'),
        ),
        migrations.AddField(
            model_name='productfeaturevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product', verbose_name='محصول'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='erp_group_code',
        ),
        migrations.AlterUniqueTogether(
            name='productfeaturevalue',
            unique_together={('product', 'feature')},
        ),
    ]
