# Generated by Django 5.2.8 on 2026-07-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_feature_productfeaturevalue_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price10',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 10'),
        ),
        migrations.AddField(
            model_name='product',
            name='price2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='price3',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='price4',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='price5',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='price6',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 6'),
        ),
        migrations.AddField(
            model_name='product',
            name='price7',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 7'),
        ),
        migrations.AddField(
            model_name='product',
            name='price8',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 8'),
        ),
        migrations.AddField(
            model_name='product',
            name='price9',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 9'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش 1'),
        ),
    ]
