# Generated by Django 5.2.8 on 2026-07-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price10_product_price2_product_price3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='عدد', max_length=50, verbose_name='واحد کالا'),
        ),
    ]
