# Generated by Django 5.2.15 on 2026-07-23 21:59

from django.db import migrations, models

from services.text import normalize_persian


def backfill_name_normalized(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        product.name_normalized = normalize_persian(product.name)
        product.save(update_fields=['name_normalized'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_fix_additional_description_collation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, verbose_name='نام برای جستجو'),
        ),
        migrations.RunPython(backfill_name_normalized, reverse_code=migrations.RunPython.noop),
    ]
