# Generated by Django 5.2.15 on 2026-07-24 18:37

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('products', '0008_warranty_alter_product_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.category_image_upload_path, verbose_name='تصویر شاخص'),
        ),
        migrations.AddField(
            model_name='category',
            name='related_blog_categories',
            field=models.ManyToManyField(blank=True, related_name='related_product_categories', to='blog.blogcategory', verbose_name='دسته\u200cبندی\u200cهای وبلاگ مرتبط'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_amazing_deals',
            field=models.BooleanField(default=True, verbose_name='نمایش شگفت\u200cانگیزها'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_banners',
            field=models.BooleanField(default=True, verbose_name='نمایش بنرها'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_best_sellers',
            field=models.BooleanField(default=True, verbose_name='نمایش پرفروش\u200cترین\u200cها'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_blog_posts',
            field=models.BooleanField(default=True, verbose_name='نمایش مطالب وبلاگی'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_frequent',
            field=models.BooleanField(default=True, verbose_name='نمایش پرتکرارها'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_suggested_categories',
            field=models.BooleanField(default=True, verbose_name='نمایش دسته\u200cبندی پیشنهادی'),
        ),
        migrations.AddField(
            model_name='category',
            name='suggested_categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent__isnull': True}, related_name='suggested_by', to='products.category', verbose_name='دسته\u200cبندی\u200cهای پیشنهادی'),
        ),
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='categories/banners/', verbose_name='تصویر بنر')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='لینک مقصد (در صورت نبود محصول)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='products.category', verbose_name='دسته\u200cبندی')),
                ('link_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product', verbose_name='محصول مقصد (اختیاری)')),
            ],
            options={
                'verbose_name': 'بنر دسته\u200cبندی',
                'verbose_name_plural': 'بنرهای دسته\u200cبندی',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='درصد تخفیف')),
                ('starts_at', models.DateTimeField(verbose_name='شروع')),
                ('ends_at', models.DateTimeField(verbose_name='پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
                'ordering': ('-starts_at',),
            },
        ),
    ]
