# Generated by Django 5.2.8 on 2026-07-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_free_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='آدرس ایمیل')),
                ('working_hours_text', models.CharField(blank=True, default='هفت روز هفته، ۲۴ ساعت شبانه\u200cروز پاسخگوی شما هستیم.', max_length=200, verbose_name='متن ساعت پاسخگویی')),
                ('footer_about_title', models.CharField(blank=True, default='فروشگاه اینترنتی هلو', max_length=200, verbose_name='عنوان درباره\u200cی فروشگاه (فوتر)')),
                ('footer_about_text', models.TextField(blank=True, default='خرید آنلاین محصولات با تحویل سریع و پشتیبانی مستقیم.', verbose_name='متن درباره\u200cی فروشگاه (فوتر)')),
                ('copyright_text', models.CharField(blank=True, default='کلیه حقوق این سایت متعلق به فروشگاه هلو می\u200cباشد.', max_length=300, verbose_name='متن کپی\u200cرایت')),
                ('enamad_link', models.URLField(blank=True, verbose_name='لینک اینماد')),
                ('trust_seal_link', models.URLField(blank=True, verbose_name='لینک نماد اعتماد الکترونیک (trust-seals)')),
                ('rubika_url', models.URLField(blank=True, verbose_name='لینک روبیکا')),
                ('aparat_url', models.URLField(blank=True, verbose_name='لینک آپارات')),
                ('bale_url', models.URLField(blank=True, verbose_name='لینک بله')),
                ('eitaa_url', models.URLField(blank=True, verbose_name='لینک ایتا')),
                ('igap_url', models.URLField(blank=True, verbose_name='لینک آی\u200cگپ')),
                ('soroush_url', models.URLField(blank=True, verbose_name='لینک سروش')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
