# Generated by Django 5.2.15 on 2026-09-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=200000, help_text='هزینه ثابت ارسال که هم در فاکتور سایت و هم به\u200cعنوان یک ردیف در فاکتور هلو ثبت می\u200cشود.', verbose_name='هزینه ارسال (تومان)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_erp_code',
            field=models.CharField(default='999999', help_text='کد کالای هزینه ارسال/بسته\u200cبندی که هنگام ثبت فاکتور در هلو استفاده می\u200cشود.', max_length=100, verbose_name='ErpCode ردیف هزینه ارسال در هلو'),
        ),
    ]
