# Generated by Django 5.2.15 on 2026-09-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_sitesettings_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notification_backend',
            field=models.CharField(choices=[('notifications.backends.console.ConsoleBackend', 'کنسول (فقط توسعه — چیزی واقعاً ارسال نمی\u200cشود)'), ('notifications.backends.kavenegar.KavenegarBackend', 'کاوه\u200cنگار'), ('notifications.backends.melipayamak.MelipayamakBackend', 'ملی\u200cپیامک (خط خدماتی اشتراکی)')], default='notifications.backends.console.ConsoleBackend', help_text='تعویض این گزینه فوری اثر می\u200cکند، بدون نیاز به تغییر کد یا ری\u200cاستارت سرور.', max_length=190, verbose_name='سرویس ارسال پیامک/اطلاع\u200cرسانی'),
        ),
    ]
