# Generated by Django 5.2.15 on 2026-09-16 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_sitesettings_notification_backend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'پیامک'), ('email', 'ایمیل')], max_length=10, verbose_name='کانال اطلاع\u200cرسانی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار موجود شدن'), ('notified', 'اطلاع داده شد')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اطلاع\u200cرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست اطلاع موجودی',
                'verbose_name_plural': 'درخواست\u200cهای اطلاع موجودی',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
