# Generated by Django 5.2.15 on 2026-09-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_stockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل اختصاصی این درخواست'),
        ),
    ]
