# Generated by Django 5.2.15 on 2026-09-18 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_stockalert_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_stories',
            field=models.BooleanField(default=True, verbose_name='نمایش بخش استوری در صفحه اصلی'),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان (زیر دایره)')),
                ('story_type', models.CharField(choices=[('image', 'عکس'), ('video', 'فیلم')], default='image', max_length=10, verbose_name='نوع استوری')),
                ('cover_image', models.ImageField(help_text='برای هر دو نوع الزامی است؛ حتی برای استوری فیلم، همین تصویر در ردیف دایره\u200cها نشان داده می\u200cشود.', upload_to='stories/covers/', verbose_name='تصویر دایره (کاور)')),
                ('image', models.ImageField(blank=True, help_text='فقط برای نوع «عکس» پر شود.', null=True, upload_to='stories/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='تصویر استوری')),
                ('video', models.FileField(blank=True, help_text='فقط برای نوع «فیلم» پر شود.', null=True, upload_to='stories/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])], verbose_name='فیلم استوری')),
                ('duration_ms', models.PositiveIntegerField(default=5000, help_text='فقط برای نوع «عکس» - مدت زمان قبل از رفتن به استوری بعدی. برای فیلم نادیده گرفته می\u200cشود (مدت واقعی فیلم استفاده می\u200cشود).', verbose_name='مدت نمایش (میلی\u200cثانیه)')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='لینک مقصد (در صورت نبود محصول)')),
                ('starts_at', models.DateTimeField(blank=True, help_text='خالی = از همین الان', null=True, verbose_name='شروع نمایش')),
                ('ends_at', models.DateTimeField(blank=True, help_text='خالی = بدون انقضا', null=True, verbose_name='پایان نمایش')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product', verbose_name='محصول مقصد (اختیاری)')),
            ],
            options={
                'verbose_name': 'استوری',
                'verbose_name_plural': 'استوری\u200cها',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
