# Generated by Django 5.2.15 on 2026-09-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_sitesettings_show_stories_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='شماره موبایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عضو خبرنامه',
                'verbose_name_plural': 'اعضای خبرنامه',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='app_bazaar_url',
            field=models.URLField(blank=True, verbose_name='لینک کافه\u200cبازار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='app_direct_download_url',
            field=models.URLField(blank=True, verbose_name='لینک دانلود مستقیم'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='app_google_play_url',
            field=models.URLField(blank=True, verbose_name='لینک گوگل\u200cپلی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='app_myket_url',
            field=models.URLField(blank=True, verbose_name='لینک مایکت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='app_sibapp_url',
            field=models.URLField(blank=True, verbose_name='لینک سیب\u200cاپ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_app_download',
            field=models.BooleanField(default=True, verbose_name='نمایش دانلود اپلیکیشن (فوتر)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_newsletter',
            field=models.BooleanField(default=True, verbose_name='نمایش عضویت در خبرنامه (فوتر)'),
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('special_offer', 'تخفیف ویژه (زیر دسته\u200cبندی)'), ('row_left', 'بنر ردیف دوتایی - سمت چپ'), ('row_right', 'بنر ردیف دوتایی - سمت راست'), ('brands', 'بنر بزرگ (زیر محبوب\u200cترین برندها)')], max_length=20, unique=True, verbose_name='جایگاه')),
                ('image', models.ImageField(upload_to='banners/home/', verbose_name='تصویر بنر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین تصویر (alt)')),
                ('link_type', models.CharField(choices=[('none', 'بدون لینک'), ('url', 'لینک دلخواه'), ('product', 'یک محصول'), ('category', 'یک دسته\u200cبندی')], default='none', max_length=10, verbose_name='نوع لینک')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='لینک دلخواه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (نمایش داده شود)')),
                ('link_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.category', verbose_name='دسته\u200cبندی مقصد')),
                ('link_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product', verbose_name='محصول مقصد')),
            ],
            options={
                'verbose_name': 'بنر صفحه اصلی',
                'verbose_name_plural': 'بنرهای صفحه اصلی',
                'ordering': ('slot',),
            },
        ),
    ]
