# Generated by Django 5.2.15 on 2026-09-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_newslettersubscriber_sitesettings_app_bazaar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockalert',
            name='channel',
            field=models.CharField(choices=[('sms', 'پیامک'), ('email', 'ایمیل'), ('both', 'پیامک و ایمیل')], max_length=10, verbose_name='کانال اطلاع\u200cرسانی'),
        ),
    ]
