# Generated by Django 5.2.15 on 2026-09-20 03:41

from django.db import migrations, models


def reset_text_defaults(apps, schema_editor):
    """
    AddField با default متنی روی ردیف‌های موجود، مقدار را داخل DDL می‌نویسد و SQL Server آن را با
    کدپیج غیر-یونیکد می‌خواند: «ی/ک» فارسی به «ي/ك» عربی تبدیل می‌شد (پس‌کرايه). مقدار پیش‌فرض
    را با ORM (پارامتر یونیکد) دوباره می‌نویسیم. در این لحظه همه‌ی ردیف‌ها تازه با default ساخته شده‌اند.
    """
    SiteSettings = apps.get_model('products', 'SiteSettings')
    SiteSettings.objects.update(**{
        name: SiteSettings._meta.get_field(name).default
        for name in ('postage_collect_label', 'postage_disabled_message')
    })


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_stockalert_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='courier_free_for_free_shipping_cart',
            field=models.BooleanField(default=True, help_text='روشن: اگر همه\u200cی کالاهای سبد «ارسال رایگان» باشند، کرایه\u200cی پیک درون\u200cشهری هم صفر می\u200cشود. خاموش: برچسب «ارسال رایگان» فقط روی پس\u200cکرایه اثر دارد و کرایه\u200cی پیک ناحیه به قوت خود باقی می\u200cماند.', verbose_name='کرایه\u200cی پیک هم برای سبدِ «ارسال رایگان» صفر شود'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='postage_collect_enabled',
            field=models.BooleanField(default=True, help_text='خاموش: به شهرهایی که ناحیه\u200cی پیک ندارند فعلاً ارسال انجام نمی\u200cشود و کاربر پیام زیر را می\u200cبیند.', verbose_name='ارسال با پست (پس\u200cکرایه) فعال باشد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='postage_collect_label',
            field=models.CharField(default='پس\u200cکرایه (پرداخت هزینه درب منزل)', help_text='این متن به\u200cجای مبلغ در فاکتور و صفحه\u200cی تسویه\u200cحساب نمایش داده می\u200cشود؛ مبلغی به فاکتور اضافه نمی\u200cشود و ردیف کرایه\u200cای هم به هلو فرستاده نمی\u200cشود.', max_length=200, verbose_name='متن پس\u200cکرایه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='postage_disabled_message',
            field=models.CharField(default='امکان ارسال به این شهر فعلاً وجود ندارد.', help_text='وقتی «ارسال با پست» خاموش است و کاربر آدرسی خارج از نواحی پیک انتخاب می\u200cکند نمایش داده می\u200cشود.', max_length=200, verbose_name='پیام غیرفعال بودن پس\u200cکرایه'),
        ),
        migrations.RunPython(reset_text_defaults, migrations.RunPython.noop),
    ]
