# Generated by Django 5.2.15 on 2026-09-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_sitesettings_shipping_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='shipping_cost',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='shipping_erp_code',
            field=models.CharField(default='999999', help_text='کد کالای هزینه ارسال که هنگام ثبت فاکتور در هلو برای سفارش\u200cهای ارسال با پیک (با کرایه\u200cی بیشتر از صفر) به\u200cعنوان یک ردیف اضافه می\u200cشود.', max_length=100, verbose_name='ErpCode ردیف کرایه\u200cی پیک در هلو'),
        ),
    ]
