# Generated by Django 5.2.15 on 2026-09-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    # جدول قدیمی Discount فقط بعد از انتقال داده‌اش به promotions.Promotion حذف می‌شود
    dependencies = [
        ('products', '0020_remove_sitesettings_shipping_cost'),
        ('promotions', '0002_migrate_legacy_discounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
