# Generated by Django 5.2.15 on 2026-09-21 19:00

from decimal import Decimal
from django.core.cache import cache
from django.db import migrations, models


def reset_text_default_and_cache(apps, schema_editor):
    """
    AddField با default متنی روی ردیف موجود، مقدار را داخل DDL می‌نویسد و SQL Server آن را با کدپیج غیر-یونیکد
    می‌خواند: «ی/ک» فارسی به «ي/ك» عربی تبدیل می‌شد (همان باگ مایگریشن 0019). متن راهنمای مهمان را با ORM
    (پارامتر یونیکد) دوباره می‌نویسیم. کش تنظیمات سایت هم پاک می‌شود، چون نسخه‌ی کش‌شده فیلدهای تازه را ندارد.
    """
    SiteSettings = apps.get_model('products', 'SiteSettings')
    SiteSettings.objects.update(
        guest_price_hidden_message=SiteSettings._meta.get_field('guest_price_hidden_message').default,
    )
    try:
        cache.delete('storefront:site_settings')
    except Exception:          # ردیس در دسترس نباشد، کش با TTL خودش (۱۵ دقیقه) تازه می‌شود
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_delete_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='guest_adjustment_type',
            field=models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت (تومان)')], default='percent', help_text='فقط در حالت «قیمت فرمولی».', max_length=10, verbose_name='نوع تعدیل قیمت مهمان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='guest_adjustment_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مثبت = افزایش، منفی = کاهش. درصدی: بین \u200e-۹۰ تا \u200e+۵۰۰ (مثلاً \u200e15 یعنی ۱۵٪ گران\u200cتر از سطح مبنا). مبلغ ثابت: عدد صحیح به تومان (مثلاً \u200e50000 یا \u200e-20000). در حالت «قیمت فرمولی» نباید صفر باشد.', max_digits=12, verbose_name='مقدار تعدیل قیمت مهمان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='guest_price_hidden_message',
            field=models.CharField(default='جهت مشاهده قیمت\u200cها و خرید وارد شوید', help_text='در حالت «مخفی\u200cسازی قیمت»، در کارت و صفحه\u200cی محصول کنار دکمه\u200cی «ورود / ثبت\u200cنام» نشان داده می\u200cشود.', max_length=200, verbose_name='متن راهنما به\u200cجای قیمت (مخفی\u200cسازی)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='guest_price_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'سطح 1 — چکی'), (2, 'سطح 2 — نقدی'), (3, 'سطح 3 — ویژه'), (4, 'سطح 4 — ویژه'), (5, 'سطح 5 — ویژه'), (6, 'سطح 6 — ویژه'), (7, 'سطح 7 — ویژه'), (8, 'سطح 8 — ویژه'), (9, 'سطح 9 — ویژه'), (10, 'سطح 10 — ویژه')], default=1, help_text='در حالت «یکی از قیمت\u200cهای ده\u200cگانه» همین سطح نمایش داده می\u200cشود و در حالت «قیمت فرمولی» مبنای تعدیل است. اگر قیمت این سطح در هلو صفر باشد، مثل بقیه\u200cی کاربران قیمت سطح ۱ (چکی) نشان داده می\u200cشود. سطح ۳ تا ۱۰ مثل کاربر ویژه حساب می\u200cشود و تخفیف خودکار نمی\u200cگیرد، مگر گزینه\u200cی «روی قیمت ویژه هم اعمال شود» در «سیاست تخفیف» روشن باشد.', verbose_name='سطح قیمت مبنا برای مهمان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='guest_price_rounding_step',
            field=models.PositiveIntegerField(choices=[(1, 'تومان'), (100, 'صد تومان'), (1000, 'هزار تومان')], default=1, help_text='قیمت حاصل از فرمول به نزدیک\u200cترین مضرب این مقدار گرد می\u200cشود (فقط حالت «قیمت فرمولی»).', verbose_name='گردکردن قیمت فرمولی مهمان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='guest_pricing_mode',
            field=models.CharField(choices=[('hide_price', 'مخفی\u200cسازی قیمت (مهمان قیمتی نمی\u200cبیند و برای مشاهده\u200cی قیمت باید وارد شود)'), ('price_level', 'نمایش یکی از قیمت\u200cهای ده\u200cگانه'), ('calculated_price', 'قیمت فرمولی (یک سطح قیمت ± درصد یا مبلغ ثابت)')], default='price_level', help_text='مهمان نمی\u200cتواند سفارش بدهد؛ این تنظیم فقط تعیین می\u200cکند چه قیمتی ببیند. در حالت «مخفی\u200cسازی» هیچ قیمتی (نه قیمت اصلی، نه خط\u200cخورده، نه مبلغ تخفیف) به مهمان نشان داده نمی\u200cشود؛ فقط درصد تخفیف.', max_length=20, verbose_name='حالت نمایش قیمت برای کاربر مهمان'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('guest_price_level__gte', 1), ('guest_price_level__lte', 10)), name='sitesettings_guest_price_level_1_to_10'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('guest_price_rounding_step__in', [1, 100, 1000])), name='sitesettings_guest_rounding_step_allowed'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest_adjustment_type', 'percent'), _negated=True), models.Q(('guest_adjustment_value__gte', Decimal('-90')), ('guest_adjustment_value__lte', Decimal('500'))), _connector='OR'), name='sitesettings_guest_percent_in_range'),
        ),
        migrations.RunPython(reset_text_default_and_cache, migrations.RunPython.noop),
    ]
