# Generated by Django 5.2.15 on 2026-09-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_sitesettings_guest_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_amount_step',
            field=models.PositiveIntegerField(default=100000, help_text='فقط در حالت «بر اساس مبلغ خرید». مبنا مبلغ خالص اقلام سفارش است (بعد از تخفیف خودکار ردیف\u200cها، بدون احتساب تخفیف کد سفارش و بدون هزینه\u200cی ارسال).', verbose_name='مبلغ هر ۱ امتیاز (تومان)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_mode',
            field=models.CharField(choices=[('order_count', 'بر اساس تعداد سفارش'), ('amount', 'بر اساس مبلغ خرید')], default='order_count', max_length=15, verbose_name='مبنای امتیازدهی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_points_per_order',
            field=models.PositiveIntegerField(default=100, help_text='فقط در حالت «بر اساس تعداد سفارش» استفاده می\u200cشود.', verbose_name='امتیاز هر سفارش موفق'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_threshold_bronze',
            field=models.PositiveIntegerField(default=300, verbose_name='آستانه\u200cی سطح برنزی (امتیاز)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_threshold_diamond',
            field=models.PositiveIntegerField(default=3000, verbose_name='آستانه\u200cی سطح الماسی (امتیاز)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_threshold_gold',
            field=models.PositiveIntegerField(default=1500, verbose_name='آستانه\u200cی سطح طلایی (امتیاز)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_threshold_silver',
            field=models.PositiveIntegerField(default=700, verbose_name='آستانه\u200cی سطح نقره\u200cای (امتیاز)'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('loyalty_threshold_bronze__lt', models.F('loyalty_threshold_silver')), ('loyalty_threshold_silver__lt', models.F('loyalty_threshold_gold')), ('loyalty_threshold_gold__lt', models.F('loyalty_threshold_diamond'))), name='sitesettings_loyalty_thresholds_ascending'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('loyalty_amount_step__gte', 1)), name='sitesettings_loyalty_amount_step_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('loyalty_points_per_order__gte', 1)), name='sitesettings_loyalty_points_per_order_gte_1'),
        ),
    ]
