# Generated by Django 5.2.15 on 2026-09-27 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_sitesettings_loyalty_amount_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_image',
            field=models.ImageField(blank=True, help_text='جایگزین فاوآیکون پیش\u200cفرض تم. خالی = همان فاوآیکون پیش\u200cفرض.', upload_to='branding/', verbose_name='فاوآیکون سفارشی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_hero_image',
            field=models.ImageField(blank=True, help_text='تصویر پس\u200cزمینه\u200cی سمت راست صفحه\u200cی ورود/ثبت\u200cنام (فقط در دسکتاپ نمایش داده می\u200cشود). خالی = تصویر پیش\u200cفرض تم.', upload_to='branding/', verbose_name='تصویر بزرگ صفحه\u200cی ورود'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='جایگزین لوگوی پیش\u200cفرض تم در هدر/فوتر (حالت روشن). خالی = همان لوگوی پیش\u200cفرض.', upload_to='branding/', verbose_name='لوگوی سفارشی سایت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_amazing_deal',
            field=models.BooleanField(default=True, verbose_name='نمایش بخش تخفیف\u200cدارها / شگفت\u200cانگیز'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_best_selling',
            field=models.BooleanField(default=True, verbose_name='نمایش بخش پرفروش\u200cترین\u200cها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_blog_posts',
            field=models.BooleanField(default=True, verbose_name='نمایش بخش مقالات و وبلاگ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_hero_slider',
            field=models.BooleanField(default=True, verbose_name='نمایش اسلایدر اصلی در صفحه اصلی'),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/slider/', verbose_name='تصویر اسلاید')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین تصویر (alt)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (نمایش داده شود)')),
                ('link_type', models.CharField(choices=[('none', 'بدون لینک'), ('url', 'لینک دلخواه'), ('product', 'یک محصول'), ('category', 'یک دسته\u200cبندی')], default='none', max_length=10, verbose_name='نوع لینک')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='لینک دلخواه')),
                ('link_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.category', verbose_name='دسته\u200cبندی مقصد')),
                ('link_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product', verbose_name='محصول مقصد')),
            ],
            options={
                'verbose_name': 'اسلاید صفحه اصلی',
                'verbose_name_plural': 'اسلایدهای صفحه اصلی',
                'ordering': ('order', 'id'),
            },
        ),
    ]
