# Generated by Django 5.2.15 on 2026-09-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_seed_default_hero_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='login_banner_subtitle',
            field=models.CharField(blank=True, default='با وارد کردن شماره موبایل خود، به سرعت وارد حساب کاربری شوید یا ثبت\u200cنام کنید.', max_length=300, verbose_name='زیرعنوان روی بنر صفحه\u200cی ورود'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_banner_title',
            field=models.CharField(blank=True, default='به فروشگاه هلو خوش آمدید', max_length=200, verbose_name='عنوان روی بنر صفحه\u200cی ورود'),
        ),
    ]
