# Generated by Django 5.2.15 on 2026-09-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_sitesettings_login_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='login_badge_icon',
            field=models.ImageField(blank=True, help_text='جایگزین آیکون Shield پیش\u200cفرض بالای فرم ورود (هم صفحه\u200cی کامل هم پاپ\u200cآپ). خالی = همان آیکون پیش\u200cفرض.', upload_to='branding/', verbose_name='آیکون نشان بالای فرم ورود'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
    ]
