# Generated by Django 5.2.15 on 2026-09-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_sitesettings_login_badge_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='return_period_days',
            field=models.PositiveIntegerField(default=7, verbose_name='مهلت مرجوعی کالا'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='return_period_unit',
            field=models.CharField(choices=[('working_days', 'روز کاری'), ('calendar_days', 'روز تقویمی')], default='working_days', help_text='روز کاری: جمعه\u200cها شمرده نمی\u200cشوند. روز تقویمی: دقیقاً N×۲۴ ساعت از لحظه\u200cی تحویل.', max_length=20, verbose_name='واحد محاسبه\u200cی مهلت مرجوعی'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('return_period_days__gte', 1)), name='sitesettings_return_period_days_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('return_period_unit__in', ['working_days', 'calendar_days'])), name='sitesettings_return_period_unit_allowed'),
        ),
    ]
