# Generated by Django 5.2.15 on 2026-09-27 08:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_sitesettings_return_period_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='return_policy_html',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='این متن عیناً در صفحه\u200cی «روش مرجوعی کالا» به مشتری نمایش داده می\u200cشود.', verbose_name='متن کامل راهنما/قوانین مرجوعی کالا'),
        ),
    ]
