# Generated by Django 5.2.15 on 2026-09-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_sitesettings_return_policy_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='return_attachment_max_image_mb',
            field=models.PositiveIntegerField(default=5, verbose_name='حداکثر حجم هر عکسِ مدرک مرجوعی (مگابایت)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='return_attachment_max_video_mb',
            field=models.PositiveIntegerField(default=50, verbose_name='حداکثر حجم هر ویدئوی مدرک مرجوعی (مگابایت)'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('return_attachment_max_image_mb__gte', 1)), name='sitesettings_return_attachment_max_image_mb_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('return_attachment_max_video_mb__gte', 1)), name='sitesettings_return_attachment_max_video_mb_gte_1'),
        ),
    ]
