# Generated by Django 5.2.15 on 2026-09-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_sitesettings_return_attachment_max_image_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_activated_at',
            field=models.DateTimeField(blank=True, help_text='در صورت خالی بودن، باشگاه مشتریان غیرفعال است و سفارشی امتیاز دریافت نمی\u200cکند.', null=True, verbose_name='تاریخ و زمان فعال\u200cسازی باشگاه مشتریان'),
        ),
    ]
