# Generated by Django 5.2.15 on 2026-09-28 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_sitesettings_loyalty_activated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_redeem_max_points_per_day',
            field=models.PositiveIntegerField(default=1000, help_text='سقف امنیتی/مالی روزانه؛ باید حداقل برابر سقف تک\u200cتراکنش باشد.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداکثر امتیاز مجاز تبدیل در روز برای هر کاربر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_redeem_max_points_per_transaction',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداکثر امتیاز مجاز در هر تراکنش تبدیل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_redeem_min_points',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداقل امتیاز مجاز برای هر بار تبدیل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_redeem_toman_per_point',
            field=models.PositiveIntegerField(default=100, help_text='هر امتیاز باشگاه هنگام تبدیل به کیف\u200cپول معادل چند تومان شارژ می\u200cشود.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='نرخ تبدیل امتیاز به کیف\u200cپول (تومان به\u200cازای هر امتیاز)'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('loyalty_redeem_toman_per_point__gte', 1)), name='sitesettings_loyalty_redeem_rate_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('loyalty_redeem_min_points__gte', 1)), name='sitesettings_loyalty_redeem_min_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('loyalty_redeem_min_points__lte', models.F('loyalty_redeem_max_points_per_transaction'))), name='sitesettings_loyalty_redeem_min_lte_max_tx'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('loyalty_redeem_max_points_per_transaction__lte', models.F('loyalty_redeem_max_points_per_day'))), name='sitesettings_loyalty_redeem_max_tx_lte_max_day'),
        ),
    ]
