# Generated by Django 5.2.15 on 2026-09-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_sitesettings_loyalty_redemption_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='loyalty_dynamic_tier_in_eligibility',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن، رتبه داینامیک باشگاه از طریق کراس\u200cواک صریح و سیاست سقف رتبه (Higher-Of) روی تخفیف\u200cها و کوپن\u200cها اعمال می\u200cشود.', verbose_name='اعمال رتبه داینامیک باشگاه در صلاحیت تخفیف\u200cها'),
        ),
    ]
