# Generated by Django 5.2.15 on 2026-09-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_sitesettings_loyalty_dynamic_tier_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_shop_columns',
            field=models.CharField(choices=[('grid-3', '۳ ستونه'), ('grid-4', '۴ ستونه')], default='grid-4', help_text='کاربر همچنان می\u200cتواند از دکمه\u200cی «نحوه نمایش» بالای صفحه\u200cی فروشگاه بین ۳/۴ ستونه یا لیستی جابه\u200cجا شود؛ این فقط پیش\u200cفرضِ اولین بازدید (پیش از ذخیره شدن ترجیح در مرورگر کاربر) را تعیین می\u200cکند.', max_length=10, verbose_name='چیدمان پیش\u200cفرض کارت\u200cهای فروشگاه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_content_max_width',
            field=models.PositiveIntegerField(default=1728, help_text='عرض بخش اصلی صفحات (هدر، فوتر، محتوا) روی صفحه\u200cنمایش\u200cهای عریض؛ هرچه بیشتر باشد فضای خالی کناره\u200cهای چپ/راست صفحه کمتر می\u200cشود. مقدار پیش\u200cفرض قبلی قالب ۱۵۳۶ پیکسل بود.', verbose_name='حداکثر عرض محتوای سایت (پیکسل)'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('site_content_max_width__gte', 960), ('site_content_max_width__lte', 2560)), name='sitesettings_content_max_width_in_range'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('default_shop_columns__in', ['grid-3', 'grid-4'])), name='sitesettings_default_shop_columns_allowed'),
        ),
    ]
