# Generated by Django 5.2.15 on 2026-09-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_sitesettings_default_shop_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='no_image_1',
            field=models.ImageField(blank=True, help_text='وقتی محصولی هیچ تصویر اصلی\u200cای از اسکنر عکس نگرفته باشد، به\u200cجای Preload.webp پیش\u200cفرض تم همین عکس در کارت/صفحه\u200cی محصول نمایش داده می\u200cشود. خالی = همان Preload.webp پیش\u200cفرض تم.', upload_to='branding/', verbose_name='تصویر پیش\u200cفرض محصول بدون عکس (نو ایمیج ۱)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='no_image_2',
            field=models.ImageField(blank=True, help_text='فقط برای محصولی که اصلاً هیچ عکسی (نه اصلی، نه گالری) ندارد؛ جلوه\u200cی هاور روی کارت این محصول به\u200cجای Preload-2.webp پیش\u200cفرض تم همین عکس را نشان می\u200cدهد. اگر محصول فقط یک عکس اصلی داشته باشد (بدون گالری)، هاور به\u200cجای این عکس، همان عکس اصلی را زوم می\u200cکند. خالی = همان Preload-2.webp پیش\u200cفرض تم.', upload_to='branding/', verbose_name='تصویر پیش\u200cفرض محصول بدون عکس (نو ایمیج ۲ / هاور)'),
        ),
    ]
