# Generated by Django 5.2.15 on 2026-09-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_sitesettings_no_image_1_sitesettings_no_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_content_max_width',
            field=models.PositiveIntegerField(default=1536, help_text='عرض صفحات پنل کاربری (حساب کاربری، سفارش\u200cها، باشگاه مشتریان و ...) - مستقل از «حداکثر عرض محتوای سایت» که فقط صفحات فروشگاهی را کنترل می\u200cکند.', verbose_name='حداکثر عرض محتوای پنل کاربری (پیکسل)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_slider_width_mode',
            field=models.CharField(choices=[('dynamic', 'متناسب با عرض سایت (هم\u200cعرض ستون اصلی محتوا)'), ('full', 'تمام عرض (لبه\u200cبه\u200cلبه، مستقل از عرض سایت)')], default='dynamic', help_text='«متناسب با عرض سایت»: اسلایدر هم\u200cعرض ستون اصلی محتوا (site_content_max_width بالا) می\u200cماند و با تغییر آن رشد/کوچک می\u200cشود. «تمام عرض»: صرف\u200cنظر از عرض محتوای سایت، اسلایدر تمام پهنای صفحه\u200cنمایش را می\u200cگیرد.', max_length=10, verbose_name='عرض اسلایدر اصلی صفحه\u200cی نخست'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_content_max_width',
            field=models.PositiveIntegerField(default=1728, help_text='عرض بخش اصلی صفحات فروشگاهی (هدر، فوتر، محتوا) روی صفحه\u200cنمایش\u200cهای عریض؛ هرچه بیشتر باشد فضای خالی کناره\u200cهای چپ/راست صفحه کمتر می\u200cشود. مقدار پیش\u200cفرض قبلی قالب ۱۵۳۶ پیکسل بود. این مقدار روی پنل کاربری اثر ندارد - نگاه کنید dashboard_content_max_width.', verbose_name='حداکثر عرض محتوای سایت (پیکسل)'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('hero_slider_width_mode__in', ['dynamic', 'full'])), name='sitesettings_hero_slider_width_mode_allowed'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('dashboard_content_max_width__gte', 960), ('dashboard_content_max_width__lte', 2560)), name='sitesettings_dashboard_content_max_width_in_range'),
        ),
    ]
