# Generated by Django 5.2.15 on 2026-09-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_sitesettings_dashboard_content_max_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_panel_max_width',
            field=models.PositiveIntegerField(blank=True, help_text='محدودکردن عرض صفحات /admin/ روی صفحه\u200cنمایش\u200cهای عریض (صفحه وسط\u200cچین می\u200cشود). خالی = بدون محدودیت، همان رفتار پیش\u200cفرض جنگو (تمام عرض). مستقل از عرض سایت و عرض پنل کاربری بالا.', null=True, verbose_name='حداکثر عرض صفحه\u200cی مدیریت جنگو (پیکسل، اختیاری)'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('admin_panel_max_width__isnull', True), models.Q(('admin_panel_max_width__gte', 960), ('admin_panel_max_width__lte', 2560)), _connector='OR'), name='sitesettings_admin_panel_max_width_in_range'),
        ),
    ]
