# Generated by Django 5.2.15 on 2026-10-01 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_sitesettings_admin_panel_max_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mega_menu_banner',
            field=models.ImageField(blank=True, help_text='در ستون کناری مگامنوی هدر، هنگام هاور روی همین دسته نمایش داده می\u200cشود. خالی = بدون بنر.', null=True, upload_to='categories/mega_banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='بنر مگامنو'),
        ),
        migrations.AddField(
            model_name='category',
            name='mega_menu_banner_alt',
            field=models.CharField(blank=True, help_text='برای دسترس\u200cپذیری و موتورهای جستجو. خالی = نام دسته\u200cبندی.', max_length=200, verbose_name='متن جایگزین بنر مگامنو'),
        ),
        migrations.AddField(
            model_name='category',
            name='mega_menu_banner_url',
            field=models.CharField(blank=True, help_text='آدرس داخلی (با / شروع شود) یا کامل (http:// یا https://). خالی = بنر بدون لینک.', max_length=500, verbose_name='لینک بنر مگامنو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_banner_width',
            field=models.PositiveSmallIntegerField(default=260, help_text='بین ۱۶۰ تا ۴۸۰.', verbose_name='عرض ستون بنر مگامنو (پیکسل)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_bg_color',
            field=models.CharField(default='#FFFFFF', help_text='پیش\u200cفرض سفید (همان ظاهر فعلی). فقط روی تم روشن اثر دارد.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'رنگ باید کد Hex شش\u200cرقمی مثل #FFFFFF باشد.')], verbose_name='رنگ پس\u200cزمینه\u200cی مگامنو (تم روشن)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_bg_image',
            field=models.ImageField(blank=True, help_text='اختیاری؛ روی رنگ پس\u200cزمینه می\u200cنشیند. خالی = بدون تصویر.', upload_to='branding/', verbose_name='تصویر پس\u200cزمینه\u200cی مگامنو (تم روشن)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_bg_image_mode',
            field=models.CharField(choices=[('cover', 'پوشش کامل (cover)'), ('repeat', 'تکرار (repeat)')], default='cover', max_length=10, verbose_name='حالت تصویر پس\u200cزمینه\u200cی مگامنو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_bg_opacity',
            field=models.PositiveSmallIntegerField(default=100, help_text='بین ۱۰ تا ۱۰۰؛ ۱۰۰ = کاملاً مات. فقط روی رنگ پس\u200cزمینه اثر دارد (نه روی عکس پس\u200cزمینه). برای افکت شیشه\u200cای مقدار کمتر از ۱۰۰ را با «بلور» ترکیب کنید.', verbose_name='شفافیت پس\u200cزمینه\u200cی مگامنو (درصد)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_blur_px',
            field=models.PositiveSmallIntegerField(default=0, help_text='بین ۰ تا ۴۰؛ ۰ = بدون بلور. وقتی معنا دارد که شفافیت کمتر از ۱۰۰ باشد.', verbose_name='میزان بلور شیشه\u200cای پشت مگامنو (پیکسل)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_columns',
            field=models.PositiveSmallIntegerField(choices=[(3, '۳ ستونه'), (4, '۴ ستونه'), (5, '۵ ستونه')], default=4, verbose_name='تعداد ستون زیردسته\u200cها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_image_gap',
            field=models.PositiveSmallIntegerField(default=8, help_text='بین ۰ تا ۳۲.', verbose_name='فاصله\u200cی تصویر تا عنوان (پیکسل)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_image_position',
            field=models.CharField(choices=[('start', 'سمت راست عنوان'), ('end', 'سمت چپ عنوان')], default='start', max_length=5, verbose_name='موقعیت تصویر نسبت به عنوان دسته'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_image_size',
            field=models.PositiveSmallIntegerField(default=32, help_text='بین ۱۶ تا ۶۴؛ مثلاً ۲۴ یا ۳۲ یا ۴۸.', verbose_name='اندازه\u200cی تصویر دسته (پیکسل)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_max_height',
            field=models.PositiveIntegerField(default=400, help_text='بین ۲۴۰ تا ۸۰۰. اگر محتوا بلندتر باشد، همان پنل اسکرول نرم اختصاصی می\u200cگیرد.', verbose_name='حداکثر ارتفاع مگامنو (پیکسل)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_show_banner',
            field=models.BooleanField(default=True, help_text='بنر هر دسته\u200cی اصلی در همان صفحه\u200cی ویرایش دسته (بخش «بنر مگامنو») تعریف می\u200cشود؛ دسته\u200cای که بنر ندارد، ستون بنرش نمایش داده نمی\u200cشود.', verbose_name='نمایش بنر دسته\u200cها در مگامنو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_show_child_images',
            field=models.BooleanField(default=False, help_text='زیردسته\u200cای که تصویر شاخص ندارد، کادر تصویرش کاملاً پنهان می\u200cشود (فضای خالی نمی\u200cماند).', verbose_name='نمایش تصویر زیردسته\u200cها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_show_parent_images',
            field=models.BooleanField(default=True, help_text='دسته\u200cای که تصویر شاخص ندارد، کادر تصویرش کاملاً پنهان می\u200cشود.', verbose_name='نمایش تصویر دسته\u200cهای اصلی (ستون راست مگامنو)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_width_mode',
            field=models.CharField(choices=[('container', 'هم\u200cعرض محتوای سایت'), ('px', 'عرض ثابت (پیکسل)'), ('percent', 'درصدی از عرض هدر')], default='container', max_length=10, verbose_name='حالت عرض مگامنو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mega_menu_width_value',
            field=models.PositiveIntegerField(default=1200, help_text='فقط وقتی «حالت عرض» روی پیکسل (۶۰۰ تا ۲۵۶۰) یا درصد (۵۰ تا ۱۰۰) باشد اعمال می\u200cشود؛ در حالت «هم\u200cعرض محتوای سایت» نادیده گرفته می\u200cشود.', verbose_name='مقدار عرض مگامنو'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('mega_menu_width_mode', 'container'), models.Q(('mega_menu_width_mode', 'px'), ('mega_menu_width_value__gte', 600), ('mega_menu_width_value__lte', 2560)), models.Q(('mega_menu_width_mode', 'percent'), ('mega_menu_width_value__gte', 50), ('mega_menu_width_value__lte', 100)), _connector='OR'), name='sitesettings_mega_menu_width_valid'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('mega_menu_max_height__gte', 240), ('mega_menu_max_height__lte', 800)), name='sitesettings_mega_menu_max_height_in_range'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('mega_menu_columns__in', [3, 4, 5])), name='sitesettings_mega_menu_columns_allowed'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('mega_menu_bg_opacity__gte', 10), ('mega_menu_bg_opacity__lte', 100)), name='sitesettings_mega_menu_bg_opacity_in_range'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('mega_menu_blur_px__gte', 0), ('mega_menu_blur_px__lte', 40)), name='sitesettings_mega_menu_blur_in_range'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('mega_menu_bg_image_mode__in', ['cover', 'repeat'])), name='sitesettings_mega_menu_bg_image_mode_allowed'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('mega_menu_image_position__in', ['start', 'end'])), name='sitesettings_mega_menu_image_position_allowed'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('mega_menu_image_size__gte', 16), ('mega_menu_image_size__lte', 64)), name='sitesettings_mega_menu_image_size_in_range'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('mega_menu_image_gap__gte', 0), ('mega_menu_image_gap__lte', 32)), name='sitesettings_mega_menu_image_gap_in_range'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('mega_menu_banner_width__gte', 160), ('mega_menu_banner_width__lte', 480)), name='sitesettings_mega_menu_banner_width_in_range'),
        ),
    ]
