# Generated by Django 5.2.15 on 2026-10-01 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


STORE_NAME_DEFAULT = 'بازرگانی موسوی'


def fix_store_name_default(apps, schema_editor):
    """
    AddField روی ردیف موجودِ تنظیمات، مقدار پیش‌فرض را به‌صورت literal بدون پیشوند N در ALTER TABLE می‌نویسد و
    SQL Server آن را با code page عربی ذخیره می‌کند (ی فارسی -> ي عربی). مقدار را با پارامتر یونیکد درست می‌نویسیم.
    فقط وقتی که مقدار تا حد اعراب/ی/ک همان پیش‌فرض باشد دست می‌زنیم؛ نامی که ادمین واقعاً عوض کرده بماند.
    """
    SiteSettings = apps.get_model('products', 'SiteSettings')
    arabic_to_persian = str.maketrans({'ي': 'ی', 'ك': 'ک'})
    for row in SiteSettings.objects.all():
        if row.store_name != STORE_NAME_DEFAULT and row.store_name.translate(arabic_to_persian) == STORE_NAME_DEFAULT:
            SiteSettings.objects.filter(pk=row.pk).update(store_name=STORE_NAME_DEFAULT)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_category_mega_menu_banner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فرستنده')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع')),
                ('message', models.TextField(max_length=2000, verbose_name='متن پیام')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP فرستنده')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('in_progress', 'در حال بررسی'), ('answered', 'پاسخ داده شد'), ('closed', 'بسته شد')], db_index=True, default='new', max_length=12, verbose_name='وضعیت بررسی')),
                ('admin_reply', models.TextField(blank=True, verbose_name='پاسخ / یادداشت مدیر')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین پاسخ')),
            ],
            options={
                'verbose_name': 'پیام تماس با ما',
                'verbose_name_plural': 'پیام\u200cهای تماس با ما',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='phone',
            new_name='store_phone_1',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='email',
            new_name='store_email_1',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='working_hours_text',
            new_name='store_working_hours',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='store_phone_1',
            field=models.CharField(blank=True, max_length=32, verbose_name='تلفن ثابت ۱'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='store_email_1',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل رسمی'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='store_working_hours',
            field=models.TextField(blank=True, default='هفت روز هفته، ۲۴ ساعت شبانه\u200cروز پاسخگوی شما هستیم.', help_text='هر خط یک ردیف. برای نمایش دوستونه (روز و ساعت) از «:» استفاده کنید، مثلاً «شنبه تا چهارشنبه: ۸ صبح تا ۱۷» و «جمعه: تعطیل». خط بدون «:» به\u200cصورت متن تمام\u200cعرض نمایش داده می\u200cشود.', verbose_name='ساعات کاری'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat1_label',
            field=models.CharField(blank=True, help_text='مثلاً سال سابقه', max_length=60, verbose_name='آمار ۱ - عنوان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat1_value',
            field=models.CharField(blank=True, help_text='مثلاً ۱۰+', max_length=20, verbose_name='آمار ۱ - عدد شاخص'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat2_label',
            field=models.CharField(blank=True, help_text='مثلاً مشتری راضی', max_length=60, verbose_name='آمار ۲ - عنوان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat2_value',
            field=models.CharField(blank=True, max_length=20, verbose_name='آمار ۲ - عدد شاخص'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat3_label',
            field=models.CharField(blank=True, help_text='مثلاً تنوع کالا', max_length=60, verbose_name='آمار ۳ - عنوان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat3_value',
            field=models.CharField(blank=True, max_length=20, verbose_name='آمار ۳ - عدد شاخص'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat4_label',
            field=models.CharField(blank=True, help_text='مثلاً رضایت مشتریان', max_length=60, verbose_name='آمار ۴ - عنوان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat4_value',
            field=models.CharField(blank=True, max_length=20, verbose_name='آمار ۴ - عدد شاخص'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_story_image',
            field=models.ImageField(blank=True, upload_to='about/', verbose_name='تصویر داستان ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_story_text',
            field=models.TextField(blank=True, help_text='هر خط خالی یک پاراگراف جدید می\u200cسازد. خالی = این بخش در صفحه نمایش داده نمی\u200cشود.', verbose_name='متن داستان ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_story_title',
            field=models.CharField(blank=True, default='داستان ما', max_length=200, verbose_name='عنوان داستان ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value1_icon',
            field=models.CharField(choices=[('quality', 'کیفیت (نمودار)'), ('price', 'قیمت (سکه)'), ('support', 'پشتیبانی (تلفن)'), ('shield', 'اطمینان (سپر)'), ('heart', 'رضایت (قلب)'), ('star', 'برتری (ستاره)')], default='quality', max_length=10, verbose_name='کارت ۱ - آیکون'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value1_text',
            field=models.TextField(blank=True, verbose_name='کارت ۱ - متن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value1_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='کارت ۱ - عنوان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value2_icon',
            field=models.CharField(choices=[('quality', 'کیفیت (نمودار)'), ('price', 'قیمت (سکه)'), ('support', 'پشتیبانی (تلفن)'), ('shield', 'اطمینان (سپر)'), ('heart', 'رضایت (قلب)'), ('star', 'برتری (ستاره)')], default='price', max_length=10, verbose_name='کارت ۲ - آیکون'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value2_text',
            field=models.TextField(blank=True, verbose_name='کارت ۲ - متن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value2_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='کارت ۲ - عنوان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value3_icon',
            field=models.CharField(choices=[('quality', 'کیفیت (نمودار)'), ('price', 'قیمت (سکه)'), ('support', 'پشتیبانی (تلفن)'), ('shield', 'اطمینان (سپر)'), ('heart', 'رضایت (قلب)'), ('star', 'برتری (ستاره)')], default='support', max_length=10, verbose_name='کارت ۳ - آیکون'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value3_text',
            field=models.TextField(blank=True, verbose_name='کارت ۳ - متن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_value3_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='کارت ۳ - عنوان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_iframe_code',
            field=models.TextField(blank=True, help_text='کد جاسازی (Embed) نقشه، مثلاً از گوگل\u200cمپ. فقط آدرس (src) آن و فقط از دامنه\u200cهای مجاز (گوگل، OpenStreetMap، نشان، بلد) با https پذیرفته می\u200cشود؛ بقیه\u200cی کد دور ریخته می\u200cشود.', verbose_name='کد iframe نقشه (برای نوع «دلخواه»)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='مثلاً 35.689197 (بین \u200e-90 تا 90).', max_digits=9, null=True, verbose_name='عرض جغرافیایی (Latitude)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='مثلاً 51.388974 (بین \u200e-180 تا 180).', max_digits=9, null=True, verbose_name='طول جغرافیایی (Longitude)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_neshan_url',
            field=models.URLField(blank=True, help_text='لینک اشتراک\u200cگذاری موقعیت از اپ نشان یا بلد؛ دکمه\u200cی «مشاهده در نشان/بلد» به همین می\u200cرود. اختیاری.', verbose_name='لینک نشان / بلد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_type',
            field=models.CharField(choices=[('google', 'نقشه\u200cی گوگل (از روی مختصات)'), ('neshan', 'نشان / بلد (نقشه\u200cی متن\u200cباز از روی مختصات + دکمه\u200cی لینک نشان/بلد)'), ('custom', 'کد iframe دلخواه')], default='google', help_text='نقشه\u200cی رسمی نشان/بلد برای جاسازی به کلید API نیاز دارد؛ بنابراین گزینه\u200cی «نشان / بلد» نقشه را از OpenStreetMap (بدون کلید) با همان مختصات نمایش می\u200cدهد و دکمه\u200cی «مشاهده در نشان/بلد» را از فیلد «لینک نشان/بلد» می\u200cسازد. با خالی بودن مختصات (یا کد iframe) نقشه نمایش داده نمی\u200cشود.', max_length=10, verbose_name='نوع نقشه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='samandehi_link',
            field=models.URLField(blank=True, verbose_name='لینک نماد ساماندهی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_address',
            field=models.TextField(blank=True, verbose_name='آدرس کامل فروشگاه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_admin_sms_recipient',
            field=models.CharField(blank=True, help_text='پیامک «پیام جدید از تماس با ما» به همین شماره می\u200cرود (فرمت 09123456789). خالی = از شماره\u200cی پیش\u200cفرض اعلان مدیر در تنظیمات سرور استفاده می\u200cشود.', max_length=11, verbose_name='شماره موبایل مدیر برای دریافت پیامک\u200cهای سیستمی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_economic_code',
            field=models.CharField(blank=True, help_text='۱۲ یا ۱۴ رقم.', max_length=14, verbose_name='کد اقتصادی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_email_2',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل پشتیبانی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_legal_name',
            field=models.CharField(blank=True, help_text='نام ثبت\u200cشده در اسناد رسمی (مثلاً «شرکت ... (سهامی خاص)»)؛ برای اسناد و فاکتور.', max_length=200, verbose_name='نام ثبتی / شخصیت حقوقی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_mobile',
            field=models.CharField(blank=True, help_text='با فرمت 09123456789.', max_length=11, verbose_name='شماره همراه فروشگاه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_name',
            field=models.CharField(default='بازرگانی موسوی', help_text='در هدر، فوتر، عنوان صفحه\u200cها (title)، متن جایگزین لوگو و صفحه\u200cهای «درباره ما» و «تماس با ما» نمایش داده می\u200cشود.', max_length=200, verbose_name='نام تجاری فروشگاه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_national_id',
            field=models.CharField(blank=True, help_text='شناسه ملی شخص حقوقی (۱۱ رقم) یا کد ملی شخص حقیقی (۱۰ رقم).', max_length=11, verbose_name='شناسه ملی / کد ملی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_phone_2',
            field=models.CharField(blank=True, max_length=32, verbose_name='تلفن ثابت ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_postal_code',
            field=models.CharField(blank=True, help_text='۱۰ رقم، بدون خط تیره.', max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_registration_number',
            field=models.CharField(blank=True, help_text='فقط رقم.', max_length=20, verbose_name='شماره ثبت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('map_type__in', ['google', 'neshan', 'custom'])), name='sitesettings_map_type_allowed'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر (اگر وارد شده بود)'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['status', 'created_at'], name='products_co_status_b4d028_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('phone', ''), _negated=True), models.Q(('email', ''), _negated=True), _connector='OR'), name='contactmessage_phone_or_email_required'),
        ),
        migrations.AddConstraint(
            model_name='contactmessage',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['new', 'in_progress', 'answered', 'closed'])), name='contactmessage_status_allowed'),
        ),
        migrations.RunPython(fix_store_name_default, migrations.RunPython.noop),
    ]
