# Generated by Django 5.2.15 on 2026-10-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_store_identity_contact_about_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='store_admin_sms_recipient_2',
            field=models.CharField(blank=True, help_text='برای اطمینان بیشتر از رسیدن پیامک؛ اگر پر باشد پیامک به هر دو شماره می\u200cرود. همان شماره\u200cی بالا را تکرار نکنید (پیامک دوبار برای یک شماره نمی\u200cرود).', max_length=11, verbose_name='شماره موبایل مدیر ۲ (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='store_admin_sms_recipient',
            field=models.CharField(blank=True, help_text='پیامک «پیام جدید از تماس با ما» به همین شماره (و شماره\u200cی دوم زیر، اگر پر باشد) می\u200cرود (فرمت 09123456789). هر دو خالی = از شماره\u200cی پیش\u200cفرض اعلان مدیر در تنظیمات سرور استفاده می\u200cشود.', max_length=11, verbose_name='شماره موبایل مدیر ۱ برای دریافت پیامک\u200cهای سیستمی'),
        ),
    ]
