# Generated by Django 5.2.15 on 2026-10-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_store_admin_sms_recipient_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_show_economic_code',
            field=models.BooleanField(default=True, verbose_name='نمایش کد اقتصادی در فاکتور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_show_legal_name',
            field=models.BooleanField(default=True, help_text='اگر خاموش یا نام ثبتی خالی باشد، نام تجاری فروشگاه در سربرگ فاکتور چاپ می\u200cشود.', verbose_name='نمایش نام حقوقی در فاکتور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_show_national_id',
            field=models.BooleanField(default=True, verbose_name='نمایش شناسه ملی در فاکتور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_show_registration_number',
            field=models.BooleanField(default=True, verbose_name='نمایش شماره ثبت در فاکتور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_show_stamp',
            field=models.BooleanField(default=True, help_text='فقط وقتی مهر چاپ می\u200cشود که تصویر مهر هم بارگذاری شده باشد.', verbose_name='نمایش مهر فروشگاه در فاکتور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_stamp_image',
            field=models.ImageField(blank=True, help_text='تصویر مهر یا امضای رسمی (ترجیحاً PNG شفاف) که پایین فاکتور چاپ می\u200cشود. اختیاری.', upload_to='branding/', verbose_name='تصویر مهر/امضای فروشگاه'),
        ),
    ]
