# Generated by Django 5.2.15 on 2026-10-04 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_invoice_stamp_and_header_switches'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_synced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='آخرین همگام\u200cسازی قیمت'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='موجودی رزروشده (سفارش\u200cهای سایت)'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_synced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='آخرین همگام\u200cسازی موجودی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stock_safety_buffer',
            field=models.PositiveSmallIntegerField(choices=[(0, 'بدون بافر'), (1, '۱ عدد'), (2, '۲ عدد')], default=0, help_text='این تعداد از موجودی هر کالا برای فروش آنلاین نگه داشته می\u200cشود (مثلاً برای فروش حضوری هم\u200cزمان در فروشگاه). با بافر ۱، کالایی که فقط ۱ عدد موجودی دارد در سایت «ناموجود» نمایش داده می\u200cشود. ۰ = بدون بافر.', verbose_name='بافر اطمینان موجودی'),
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveBigIntegerField(db_index=True, verbose_name='شناسه سفارش')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('state', models.CharField(choices=[('held', 'رزرو شده'), ('invoiced', 'فاکتور در هلو ثبت شد (تا سینک بعدی نگه\u200cداشته می\u200cشود)'), ('expired', 'منقضی شد'), ('released', 'آزاد شد')], db_index=True, default='held', max_length=10, verbose_name='وضعیت')),
                ('expires_at', models.DateTimeField(blank=True, help_text='خالی = تا تصمیم مدیر (سفارش پرداخت\u200cشده/چکی) یا آزادسازی پس از سینک می\u200cماند.', null=True, verbose_name='انقضای رزرو')),
                ('invoiced_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت فاکتور در هلو')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان آزادسازی')),
                ('release_reason', models.CharField(blank=True, default='', max_length=60, verbose_name='دلیل آزادسازی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'رزرو موجودی',
                'verbose_name_plural': 'رزروهای موجودی',
                'ordering': ('-id',),
                'constraints': [models.UniqueConstraint(fields=('order_id', 'product'), name='stockreservation_one_row_per_order_product'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stockreservation_quantity_gt_0')],
            },
        ),
    ]
