# Generated by Django 5.2.15 on 2026-10-04 14:22

from django.db import migrations, models


def fix_placeholder_shipping_erp_code(apps, schema_editor):
    """ مقدار پیش‌فرض قدیمی '999999' در هلو وجود ندارد (خطای «کد کالا نامعتبر»)؛ با ErpCode واقعیِ کالای «سرويس» جایگزین می‌شود """
    SiteSettings = apps.get_model('products', 'SiteSettings')
    SiteSettings.objects.filter(shipping_erp_code='999999').update(shipping_erp_code='bBALNA1mckd7Zh4O')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_stock_reservation_and_safety_buffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='holoo_pos_sarfasl',
            field=models.CharField(default='10200010004', help_text='سرفصل حساب بانکیِ دارای کارتخوان در هلو که فاکتور سفارش\u200cهای پرداخت\u200cشده با آن تسویه می\u200cشود.', max_length=30, verbose_name='سرفصل کارتخوانِ پرداخت آنلاین در هلو'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='shipping_erp_code',
            field=models.CharField(default='bBALNA1mckd7Zh4O', help_text='ErpCode کالای خدماتی هزینه ارسال (در هلو: «سرويس») که هنگام ثبت فاکتور برای سفارش\u200cهای ارسال با پیک (با کرایه\u200cی بیشتر از صفر) به\u200cعنوان یک ردیف اضافه می\u200cشود. باید ErpCode واقعیِ همان کالا در هلو باشد، نه «کد کالا».', max_length=100, verbose_name='ErpCode ردیف کرایه\u200cی پیک در هلو'),
        ),
        migrations.RunPython(fix_placeholder_shipping_erp_code, migrations.RunPython.noop),
    ]
