# Generated by Django 5.2.15 on 2026-10-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_holoo_real_integration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cart_fly_animation_enabled',
            field=models.BooleanField(default=True, help_text='با زدن «افزودن به سبد»، عکس محصول از کارت بیرون می\u200cآید، داخل یک سبد می\u200cافتد و سبد به آیکون سبد خرید می\u200cرود و پنجره\u200cی کوچک سبد چند ثانیه باز می\u200cماند. خاموش = رفتار ساده\u200cی قبلی (فقط شمارنده عوض می\u200cشود).', verbose_name='افکت پرواز محصول به سبد خرید'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cart_fly_respect_reduced_motion',
            field=models.BooleanField(default=False, help_text='اگر روشن باشد و کاربر در سیستم\u200cعاملش انیمیشن\u200cها را خاموش کرده باشد (ویندوز: تنظیمات ← دسترسی\u200cپذیری ← جلوه\u200cهای بصری)، فقط پنجره\u200cی سبد نشان داده می\u200cشود و عکس پرواز نمی\u200cکند. پیش\u200cفرض خاموش است چون افکت کوتاه است و فقط با کلیک خودِ کاربر اجرا می\u200cشود؛ روی بسیاری از رایانه\u200cها (از جمله سرورهای ویندوز و ریموت دسکتاپ) این گزینه\u200cی سیستم ناخواسته فعال است و افکت دیده نمی\u200cشد.', verbose_name='رعایت «کاهش حرکت» سیستم\u200cعامل در افکت سبد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cart_hover_popup_enabled',
            field=models.BooleanField(default=True, help_text='کاربر دسکتاپ با نگه داشتن ماوس روی آیکون سبد خرید هدر، همان پنجره\u200cی کوچک سبد را می\u200cبیند (عکس کالاها، تعداد، جمع کل). روی موبایل/لمسی اثری ندارد. کلیک روی آیکون همچنان کشوی کامل سبد را باز می\u200cکند. فقط برای کاربر واردشده.', verbose_name='باز شدن پنجره\u200cی سبد با رفتن ماوس روی آیکون سبد (دسکتاپ)'),
        ),
    ]
