# Generated by Django 5.2.15 on 2026-10-07 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_cart_fly_animation_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_admin_sms_cooldown_minutes',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='فاصله\u200cی حداقلی پیامک به کارشناس (دقیقه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_ai_coming_soon_text',
            field=models.CharField(default='دستیار هوشمند فروشگاه به\u200cزودی در خدمت شماست.', max_length=240, verbose_name='متن زبانه\u200cی «چت هوشمند» (به\u200cزودی)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_ai_tab_mode',
            field=models.CharField(choices=[('hidden', 'مخفی\u200cسازی کامل'), ('coming_soon', 'نمایش با نشان «به\u200cزودی»')], default='coming_soon', help_text='فعلاً دستیار هوشمند ساخته نشده؛ یا با نشان «به\u200cزودی» دیده می\u200cشود یا کاملاً پنهان است.', max_length=12, verbose_name='زبانه\u200cی «چت هوشمند»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_anim_bubble',
            field=models.BooleanField(default=True, verbose_name='حباب پیام متحرک کنار دکمه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_anim_enabled',
            field=models.BooleanField(default=True, help_text='خاموش = هیچ حرکتی (شناوری، نبض، دست\u200cتکان\u200cدادن، حباب متحرک) اجرا نمی\u200cشود؛ بر همه\u200cی گزینه\u200cهای زیر غلبه دارد.', verbose_name='انیمیشن\u200cهای ویجت (خاموش کردن همه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_anim_float',
            field=models.BooleanField(default=True, verbose_name='شناوری ملایم دکمه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_anim_pulse',
            field=models.BooleanField(default=True, verbose_name='نبض (حلقه\u200cی جلب\u200cتوجه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_anim_wave',
            field=models.BooleanField(default=True, verbose_name='دست\u200cتکان\u200cدادن کاراکتر (فقط آواتار کاراکتر)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_assignee_timeout_minutes',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='غیبت پیوسته\u200cی کارشناس مسئول تا بازگشت به صف (دقیقه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_attachment_max_count',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='حداکثر تعداد فایل در هر پیام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_attachment_max_mb',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='حداکثر حجم هر فایل (مگابایت)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_attachments_enabled',
            field=models.BooleanField(default=False, verbose_name='ارسال پیوست در گفتگو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_attachments_mode',
            field=models.CharField(choices=[('images', 'فقط تصاویر (JPG/PNG/WebP)'), ('images_docs', 'تصاویر + PDF')], default='images', max_length=12, verbose_name='نوع فایل\u200cهای مجاز'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_attention_interval_seconds',
            field=models.PositiveSmallIntegerField(default=20, help_text='نبض و دست\u200cتکان\u200cدادن حلقه\u200cی بی\u200cپایان نیستند؛ هر چند ثانیه یک بار حدود ۳ ثانیه اجرا می\u200cشوند.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)], verbose_name='فاصله\u200cی جلب\u200cتوجه (نبض و دست\u200cتکان\u200cدادن) (ثانیه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_avatar_choice',
            field=models.CharField(choices=[('support', 'پشتیبان خندان با هدست'), ('character', 'کاراکتر تمام\u200cقد با دست\u200cتکان\u200cدادن'), ('custom', 'تصویر اختصاصی (آپلود)')], default='support', max_length=10, verbose_name='آواتار دکمه\u200cی شناور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_avatar_custom',
            field=models.ImageField(blank=True, help_text='فقط وقتی «تصویر اختصاصی» انتخاب شده استفاده می\u200cشود. JPG/PNG/WebP، ترجیحاً مربع (SVG پذیرفته نمی\u200cشود).', null=True, upload_to='chat/avatar/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='آواتار اختصاصی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_bubble_first_delay_seconds',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(60)], verbose_name='تأخیر نمایش اولین حباب (ثانیه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_bubble_interval_seconds',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(120)], verbose_name='فاصله\u200cی تعویض حباب (ثانیه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_bubble_messages',
            field=models.TextField(blank=True, default='سلام! کمکی از من برمیاد؟\nسؤالی درباره\u200cی قیمت یا سفارش دارید؟\nپیام بگذارید، پاسخ می\u200cدهیم.', help_text='حداکثر ۲۰ خط و هر خط ۱۲۰ نویسه. خالی = حباب نمایش داده نمی\u200cشود.', verbose_name='متن\u200cهای حباب (هر خط یکی، به\u200cترتیب می\u200cچرخند)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_captcha_after_n_conversations',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='کپچا بعد از چند گفتگو (۰ = هرگز)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_continuity_minutes',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='پنجره\u200cی پیوستگی گفتگو (دقیقه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_customer_gone_minutes',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name='رفتن مشتری تا حالت آفلاین (دقیقه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_customer_idle_minutes',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='بی\u200cپاسخی مشتری تا «منتظر مشتری» (دقیقه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_customer_sms_cooldown_minutes',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='فاصله\u200cی حداقلی پیامک به مشتری (دقیقه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_enabled',
            field=models.BooleanField(default=False, help_text='خاموش = هیچ ویجتی در سایت نمی\u200cآید. توجه: در این مرحله فقط ظاهر ویجت آماده است؛ ثبت و ارسال پیام و پاسخ زنده در مراحل بعدی فعال می\u200cشود.', verbose_name='فعال بودن گفتگوی آنلاین (کلید اصلی)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_excluded_paths',
            field=models.TextField(blank=True, default='/orders/checkout/*\n/payments/*', help_text='هر خط یک الگو: «/orders/checkout/» مسیر دقیق، «/payments/*» همه\u200cی مسیرهای زیرمجموعه، «name:orders:checkout» نام URL. خط\u200cهایی که با # شروع شوند نادیده\u200cاند. در صفحه\u200cی مستثنی هیچ کد و اسکریپتی از چت بارگذاری نمی\u200cشود.', verbose_name='صفحات مستثنی (ویجت در این\u200cها لود نشود)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_guest_max_conversations_per_day',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='سقف گفتگوی جدید در روز (هر IP)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_guest_name_mode',
            field=models.CharField(choices=[('hidden', 'نمایش داده نشود'), ('optional', 'اختیاری'), ('required', 'اجباری')], default='optional', max_length=8, verbose_name='کادر نام (مهمان)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_guest_phone_mode',
            field=models.CharField(choices=[('hidden', 'نمایش داده نشود'), ('optional', 'اختیاری'), ('required', 'اجباری')], default='optional', max_length=8, verbose_name='کادر موبایل (مهمان)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_holidays',
            field=models.TextField(blank=True, default='', help_text='هر خط یک روز: «1405/07/21 عنوان اختیاری». در این روزها همیشه «خارج از ساعت کاری» است.', verbose_name='روزهای تعطیل (تاریخ جلالی)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_hours_fri',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='ساعات جمعه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_hours_mode',
            field=models.CharField(choices=[('always', 'همیشه (۲۴ ساعته)'), ('by_schedule', 'طبق برنامه\u200cی هفتگی و تعطیلات')], default='by_schedule', max_length=12, verbose_name='حالت ساعات کاری'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_hours_mon',
            field=models.CharField(blank=True, default='08:00-12:00, 13:00-17:00', max_length=80, verbose_name='ساعات دوشنبه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_hours_sat',
            field=models.CharField(blank=True, default='08:00-12:00, 13:00-17:00', help_text='چند بازه با ویرگول؛ مثل 08:00-12:00, 13:00-17:00. خالی = تعطیل.', max_length=80, verbose_name='ساعات شنبه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_hours_sun',
            field=models.CharField(blank=True, default='08:00-12:00, 13:00-17:00', max_length=80, verbose_name='ساعات یکشنبه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_hours_thu',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='ساعات پنجشنبه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_hours_tue',
            field=models.CharField(blank=True, default='08:00-12:00, 13:00-17:00', max_length=80, verbose_name='ساعات سه\u200cشنبه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_hours_wed',
            field=models.CharField(blank=True, default='08:00-12:00, 13:00-17:00', max_length=80, verbose_name='ساعات چهارشنبه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_idle_close_hours',
            field=models.PositiveSmallIntegerField(default=48, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)], verbose_name='بستن خودکار گفتگوی بی\u200cفعالیت (ساعت)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_launcher_dismiss_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='کاربر با ضربدر کوچک دکمه را می\u200cبندد؛ این مدت در مرورگر خودش یادآوری می\u200cشود. ۰ = فقط تا بستن صفحه.', validators=[django.core.validators.MaxValueValidator(720)], verbose_name='مدت مخفی ماندن بعد از بستن دکمه (ساعت)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_live_requires_operator',
            field=models.BooleanField(default=True, help_text='خاموش = در ساعت کاری، گفتگوی زنده حتی بدون کارشناس آنلاین هم شروع می\u200cشود و در صف می\u200cماند.', verbose_name='گفتگوی زنده فقط وقتی کارشناس آنلاین است'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_message_max_length',
            field=models.PositiveSmallIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(4000)], verbose_name='حداکثر طول هر پیام (نویسه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_message_placeholder',
            field=models.CharField(default='پیام خود را بنویسید…', max_length=60, verbose_name='متن راهنمای کادر پیام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_msg_after_hours',
            field=models.TextField(default='اکنون خارج از ساعت پاسخگویی هستیم. پیام خود را بگذارید تا در اولین فرصت پاسخ دهیم.', verbose_name='پیام «خارج از ساعت کاری»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_msg_no_operator',
            field=models.TextField(default='در حال حاضر کارشناس آنلاینی در دسترس نیست. پیام خود را بگذارید؛ پاسخ را در همین ویجت و (برای کاربران واردشده) با پیامک دریافت می\u200cکنید.', verbose_name='پیام «کارشناس در دسترس نیست» (ساعت کاری)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_name_placeholder',
            field=models.CharField(default='نام شما', max_length=40, verbose_name='متن راهنمای کادر نام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_notify_phones',
            field=models.TextField(blank=True, default='', help_text='خالی = همان شماره\u200cی پیش\u200cفرض اعلان مدیر. روشن/خاموش بودن و متن پیامک\u200cها در «اطلاع\u200cرسانی ← تنظیمات انواع پیام» است.', verbose_name='شماره\u200cهای کارشناسان برای پیامک (هر خط یکی)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_offline_form_intro',
            field=models.CharField(default='پیام خود را بنویسید؛ کارشناسان ما در اولین فرصت پاسخ می\u200cدهند.', max_length=240, verbose_name='مقدمه\u200cی فرم پیام آفلاین'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_offline_success_message',
            field=models.CharField(default='پیام شما ثبت شد. پاسخ را همین\u200cجا و (برای کاربران واردشده) با پیامک دریافت می\u200cکنید.', max_length=240, verbose_name='پیام موفقیت ثبت پیام آفلاین'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_offset_x_px',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='فاصله از لبه\u200cی کناری - دسکتاپ (پیکسل)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_offset_x_px_mobile',
            field=models.PositiveSmallIntegerField(blank=True, help_text='خالی = خودکار (همان فاصله\u200cی دسکتاپ).', null=True, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='فاصله از لبه\u200cی کناری - موبایل (پیکسل)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_offset_y_px',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='فاصله از پایین صفحه - دسکتاپ (پیکسل)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_offset_y_px_mobile',
            field=models.PositiveSmallIntegerField(blank=True, help_text='خالی = خودکار: بالای منوی پایین موبایل می\u200cنشیند و روی آن نمی\u200cافتد.', null=True, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='فاصله از پایین صفحه - موبایل (پیکسل)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_operator_response_sla_minutes',
            field=models.PositiveSmallIntegerField(default=10, help_text='بعد از این مدت بدون پاسخ، گفتگو به حالت «آفلاین (ناهمزمان)» می\u200cرود. ۰ = غیرفعال.', validators=[django.core.validators.MaxValueValidator(240)], verbose_name='مهلت پاسخ کارشناس (دقیقه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_operator_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(600)], verbose_name='مهلت نبض کارشناس برای «آنلاین» ماندن (ثانیه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_phone_placeholder',
            field=models.CharField(default='شماره موبایل (09123456789)', max_length=40, verbose_name='متن راهنمای کادر موبایل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_poll_active_seconds',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)], verbose_name='فاصله\u200cی به\u200cروزرسانی - پنجره\u200cی باز (ثانیه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_poll_closed_seconds',
            field=models.PositiveSmallIntegerField(default=60, help_text='۰ = وقتی پنجره بسته است اصلاً درخواست نمی\u200cفرستد؛ وگرنه بین ۱۵ تا ۶۰۰.', validators=[django.core.validators.MaxValueValidator(600)], verbose_name='فاصله\u200cی به\u200cروزرسانی - پنجره\u200cی بسته (ثانیه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_poll_idle_seconds',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(120)], verbose_name='فاصله\u200cی به\u200cروزرسانی - کاربر بی\u200cفعالیت (ثانیه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_position',
            field=models.CharField(choices=[('left', 'پایین چپ'), ('right', 'پایین راست')], default='left', max_length=5, verbose_name='سمت دکمه\u200cی شناور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_primary_color',
            field=models.CharField(default='#FF8229', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'رنگ باید کد Hex شش\u200cرقمی مثل #FF8229 باشد.')], verbose_name='رنگ اصلی ویجت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_privacy_notice',
            field=models.CharField(blank=True, default='', help_text='مثلاً «با ارسال پیام، با ذخیره\u200cی گفتگو برای پشتیبانی موافقت می\u200cکنید.» خالی = نمایش داده نمی\u200cشود.', max_length=240, verbose_name='یادداشت حریم خصوصی (زیر فرم)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_rate_limit_per_minute',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='سقف تعداد پیام در دقیقه (هر بازدیدکننده)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_reopen_on_customer_message',
            field=models.BooleanField(default=True, verbose_name='پیام مشتری گفتگوی بسته را بازگشایی کند'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_reopen_window_hours',
            field=models.PositiveSmallIntegerField(default=72, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)], verbose_name='مهلت بازگشایی گفتگوی بسته (ساعت)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_respect_reduced_motion',
            field=models.BooleanField(default=True, help_text='روشن (پیشنهادی): کاربری که در سیستمش انیمیشن را خاموش کرده هیچ حرکتی نمی\u200cبیند. ', verbose_name='رعایت «کاهش حرکت» سیستم\u200cعامل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_retention_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='۰ = برای همیشه نگه داشته شود.', validators=[django.core.validators.MaxValueValidator(3650)], verbose_name='نگهداری گفتگوها (روز)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_send_label',
            field=models.CharField(default='ارسال پیام', max_length=24, verbose_name='برچسب دکمه\u200cی ارسال'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_subtitle_offline',
            field=models.CharField(default='کارشناسان در دسترس نیستند؛ پیام بگذارید', max_length=120, verbose_name='زیرعنوان (آفلاین)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_subtitle_online',
            field=models.CharField(default='آنلاین؛ معمولاً در چند دقیقه پاسخ می\u200cدهیم', max_length=120, verbose_name='زیرعنوان (آنلاین)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_tab_ai_label',
            field=models.CharField(default='چت هوشمند', max_length=24, verbose_name='برچسب زبانه\u200cی چت هوشمند'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_tab_live_enabled',
            field=models.BooleanField(default=True, verbose_name='زبانه\u200cی «گفتگوی آنلاین»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_tab_live_label',
            field=models.CharField(default='گفتگوی آنلاین', max_length=24, verbose_name='برچسب زبانه\u200cی گفتگوی آنلاین'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_tab_offline_enabled',
            field=models.BooleanField(default=True, verbose_name='زبانه\u200cی «پیام آفلاین»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_tab_offline_label',
            field=models.CharField(default='پیام آفلاین', max_length=24, verbose_name='برچسب زبانه\u200cی پیام آفلاین'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_timezone',
            field=models.CharField(default='Asia/Tehran', help_text='نام استاندارد IANA، مثل Asia/Tehran. ساعات کاری و تعطیلات بر پایه\u200cی همین ساعت محاسبه می\u200cشوند.', max_length=40, verbose_name='منطقه\u200cی زمانی چت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_title',
            field=models.CharField(default='پشتیبانی بازرگانی موسوی', max_length=60, verbose_name='عنوان پنجره'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_to_offline_label',
            field=models.CharField(default='ارسال پیام آفلاین', max_length=40, verbose_name='برچسب دکمه\u200cی رفتن به فرم آفلاین'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_visible_for_guests',
            field=models.BooleanField(default=True, verbose_name='نمایش برای مهمان\u200cها (لاگین\u200cنکرده)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_visible_for_users',
            field=models.BooleanField(default=True, verbose_name='نمایش برای کاربران واردشده'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_welcome_message',
            field=models.CharField(default='سلام! به بازرگانی موسوی خوش آمدید. چطور می\u200cتوانیم کمکتان کنیم؟', max_length=240, verbose_name='پیام خوشامد'),
        ),
    ]
