# Generated by Django 5.2.15 on 2026-10-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_chat_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_close_conversation_label',
            field=models.CharField(default='پایان گفتگو', max_length=40, verbose_name='برچسب دکمه\u200cی پایان گفتگو'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='chat_enabled',
            field=models.BooleanField(default=False, help_text='خاموش = هیچ ویجتی در سایت نمی\u200cآید. پیام آفلاین و پاسخ کارشناس فعال است؛ گفتگوی زنده در مرحله\u200cی بعد اضافه می\u200cشود.', verbose_name='فعال بودن گفتگوی آنلاین (کلید اصلی)'),
        ),
    ]
