# Generated by Django 5.2.15 on 2026-10-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_chat_close_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_live_form_intro',
            field=models.CharField(default='با یک کارشناس گفتگو کنید؛ معمولاً در چند دقیقه پاسخ می\u200cدهیم.', max_length=240, verbose_name='مقدمه\u200cی فرم گفتگوی زنده'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_live_waiting_text',
            field=models.CharField(default='گفتگوی شما ثبت شد؛ کارشناس به\u200cزودی به شما می\u200cپیوندد.', max_length=240, verbose_name='پیام «در انتظار کارشناس» (گفتگوی زنده)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_typing_indicator_enabled',
            field=models.BooleanField(default=True, help_text='فقط یک علامت زنده\u200cی کوتاه است و در دیتابیس ذخیره نمی\u200cشود؛ اگر Redis قطع باشد خودکار نمایش داده نمی\u200cشود.', verbose_name='نشانگر «در حال نوشتن» فعال باشد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_typing_text',
            field=models.CharField(default='کارشناس در حال نوشتن…', max_length=60, verbose_name='متن نشانگر «در حال نوشتن»'),
        ),
    ]
