# Generated by Django 5.2.15 on 2026-10-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_chat_live_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_blocked_message',
            field=models.CharField(default='امکان ارسال پیام برای شما محدود شده است. در صورت اشتباه، از راه\u200cهای ارتباطی دیگر با ما تماس بگیرید.', max_length=240, verbose_name='پیام کاربر مسدودشده'),
        ),
    ]
