# Generated by Django 5.2.15 on 2026-10-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_chat_attachments_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='vip_cheque_policy',
            field=models.CharField(choices=[('disabled', 'غیرفعال (فقط پرداخت نقدی/آنلاین با قیمت ویژه)'), ('direct_check_vip_price', 'خرید چکی مستقیم، با حفظ قیمت اختصاصی ویژه'), ('direct_check_standard_price', 'خرید چکی مستقیم، با قیمت مصوب چکی (سطح ۱)'), ('request_check', 'فقط «درخواست خرید چکی» (هدایت به ثبت درخواست اعتباری)')], default='disabled', help_text='تعیین می\u200cکند مشتری ویژه در تسویه حساب چه گزینه\u200cای برای چکی ببیند. پیش\u200cفرض امن: غیرفعال. اگر برای یک کاربر «مجوز خرید چکی» فعال شده باشد، آن مجوز (با قیمت اختصاصی ویژه) بر این سیاست اولویت دارد.', max_length=30, verbose_name='خرید چکی مشتریان ویژه (VIP)'),
        ),
    ]
