# Generated by Django 5.2.15 on 2026-10-08 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_cheque_settlement_separation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cheque_submission_deadline_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='مشتری باید ظرف این مدت پس از ثبت سفارش چکی، اطلاعات و تصویر دست\u200cکم یک چک را ثبت کند؛ وگرنه سفارش خودکار لغو و موجودی رزروشده آزاد می\u200cشود. با ثبت اولین چک، مهلت متوقف می\u200cشود. ۰ = بدون مهلت (لغو خودکار خاموش). حداکثر ۷۲۰ ساعت (۳۰ روز).', validators=[django.core.validators.MaxValueValidator(720)], verbose_name='مهلت ثبت اطلاعات چک (ساعت)'),
        ),
    ]
