# Generated by Django 5.2.15 on 2026-10-08 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_cheque_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cheque_credit_docs_retention_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='تصاویر مدارک (دسته\u200cچک، کارت ملی، ...) این\u200cقدر روز پس از تعیین\u200cتکلیف نهایی درخواست (تأیید، رد یا انصراف) به\u200cصورت خودکار پاک می\u200cشوند؛ اطلاعات متنی درخواست می\u200cماند. ۰ = پاک\u200cسازی خودکار خاموش (مدارک نگه داشته می\u200cشوند).', validators=[django.core.validators.MaxValueValidator(3650)], verbose_name='مدت نگهداری مدارک درخواست خرید چکی (روز)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='strict_national_code_validation',
            field=models.BooleanField(default=True, help_text='روشن: کد ملی پروفایل مشتری هنگام ثبت درخواست خرید چکی با الگوریتم رسمی (رقم کنترل) سنجیده می\u200cشود و کد نامعتبر پذیرفته نمی\u200cشود. خاموش: فقط ده\u200cرقمی بودن کافی است (مثلاً برای مشتریان واردشده از هلو که کد ملی\u200cشان ممکن است درست ثبت نشده باشد). فعلاً فقط روی درخواست خرید چکی اثر دارد.', verbose_name='اعتبارسنجی سخت\u200cگیرانه رقم کنترلی کدملی'),
        ),
    ]
