# Generated by Django 5.2.15 on 2026-10-10 21:53

import products.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_cheque_credit_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, storage=products.storage.versioned_media_storage, upload_to='products/main/', verbose_name='تصویر اصلی سایت'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=products.storage.versioned_media_storage, upload_to='products/gallery/', verbose_name='تصویر'),
        ),
    ]
